<?php

declare(strict_types=1);

namespace SqlcPhp\SchemaExtractor;

use SqlcPhp\Config\DatabaseConfig;
use SqlcPhp\Version;

/**
 * Extracts CREATE TABLE / CREATE VIEW schema from a MySQL / MariaDB database.
 *
 * Uses SHOW TABLES to enumerate tables and SHOW CREATE TABLE to get each
 * definition — the same DDL format that SchemaParser already understands.
 *
 * Post-processing:
 *   - AUTO_INCREMENT=N stripped from table options (resets on each dump,
 *     would create noisy diffs in git).
 *   - The charset/collation suffix is preserved so type inference remains exact.
 */
class MySQLSchemaExtractor implements SchemaExtractorInterface
{
    public function extract(\PDO $pdo, DatabaseConfig $cfg): string
    {
        // Fetch current database name for the header comment
        $dbName = $pdo->query('SELECT DATABASE()')->fetchColumn() ?: 'unknown';

        $tables = $this->listTables($pdo);

        if (empty($tables)) {
            throw new \RuntimeException(
                "No tables found in database '{$dbName}'. " .
                "Ensure the DSN points to the correct database."
            );
        }

        // Apply include/exclude filters
        $filtered = array_filter($tables, fn(string $t) => $cfg->shouldInclude($t));
        $filtered = array_values($filtered);

        if (empty($filtered)) {
            throw new \RuntimeException(
                "All tables were filtered out by include_tables / exclude_tables. " .
                "Found: " . implode(', ', $tables)
            );
        }

        $lines = [];
        $lines[] = '-- -------------------------------------------------------------------------';
        $lines[] = '-- Schema generated by sqlc-php v' . Version::VERSION . ' --generate-schema';
        $lines[] = '-- Database : ' . $dbName;
        $lines[] = '-- Tables   : ' . count($filtered) . ' (of ' . count($tables) . ' total)';
        $lines[] = '-- Generated: ' . date('Y-m-d H:i:s');
        $lines[] = '--';
        $lines[] = '-- Do not edit manually — regenerate with: sqlc-php --generate-schema';
        $lines[] = '-- -------------------------------------------------------------------------';
        $lines[] = '';

        foreach ($filtered as $tableName) {
            $ddl = $this->showCreateTable($pdo, $tableName);
            $ddl = $this->cleanDdl($ddl);
            $lines[] = $ddl . ';';
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    // -------------------------------------------------------------------------

    /**
     * @return string[]  Table names in the current database
     */
    private function listTables(\PDO $pdo): array
    {
        $stmt = $pdo->query('SHOW TABLES');
        if ($stmt === false) {
            throw new \RuntimeException('SHOW TABLES failed — check database permissions.');
        }
        return $stmt->fetchAll(\PDO::FETCH_COLUMN) ?: [];
    }

    private function showCreateTable(\PDO $pdo, string $tableName): string
    {
        // Use backtick-quoted identifier to handle reserved word table names
        $safe = '`' . str_replace('`', '``', $tableName) . '`';
        $stmt = $pdo->query("SHOW CREATE TABLE {$safe}");

        if ($stmt === false) {
            throw new \RuntimeException("SHOW CREATE TABLE failed for table '{$tableName}'.");
        }

        $row = $stmt->fetch(\PDO::FETCH_ASSOC);

        if ($row === false) {
            throw new \RuntimeException("Empty result from SHOW CREATE TABLE '{$tableName}'.");
        }

        // Column index 1 is "Create Table"; for views it's "Create View"
        return $row['Create Table'] ?? $row['Create View'] ?? array_values($row)[1] ?? '';
    }

    /**
     * Post-process DDL to remove values that change between dumps and would
     * create spurious git diffs without affecting the PHP type generation.
     */
    private function cleanDdl(string $ddl): string
    {
        // Remove AUTO_INCREMENT=<n> from table options
        // e.g. ) ENGINE=InnoDB AUTO_INCREMENT=42 DEFAULT CHARSET=utf8mb4
        $ddl = preg_replace('/\s+AUTO_INCREMENT=\d+/i', '', $ddl) ?? $ddl;

        return rtrim($ddl);
    }
}
