<?php

declare(strict_types=1);

namespace SqlcPhp\SchemaExtractor;

use SqlcPhp\Config\DatabaseConfig;
use SqlcPhp\Version;

/**
 * Extracts CREATE TABLE and CREATE VIEW schema from a MySQL / MariaDB database.
 *
 * Uses SHOW FULL TABLES to enumerate objects and distinguish between
 * BASE TABLE and VIEW types, then uses SHOW CREATE TABLE / SHOW CREATE VIEW
 * to get each DDL definition — the same format SchemaParser already understands.
 *
 * Views are only included when include_views: true is set in the database config.
 *
 * Post-processing:
 *   - AUTO_INCREMENT=N stripped from table options (resets on each dump).
 *   - DEFINER clause stripped from CREATE VIEW (user-specific, causes diffs).
 *   - SQL SECURITY clause stripped from CREATE VIEW (irrelevant for type gen).
 *   - ALGORITHM= clause stripped from CREATE VIEW (execution detail).
 *   - The output separates tables and views into clearly marked sections.
 */
class MySQLSchemaExtractor implements SchemaExtractorInterface
{
    public function extract(\PDO $pdo, DatabaseConfig $cfg): string
    {
        // Fetch current database name for the header comment
        $dbName = $pdo->query('SELECT DATABASE()')->fetchColumn() ?: 'unknown';

        ['tables' => $allTables, 'views' => $allViews] = $this->listObjects($pdo);

        if (empty($allTables) && empty($allViews)) {
            throw new \RuntimeException(
                "No tables or views found in database '{$dbName}'. " .
                "Ensure the DSN points to the correct database."
            );
        }

        // Apply include/exclude filters
        $tables = array_values(array_filter($allTables, fn(string $t) => $cfg->shouldInclude($t)));
        $views  = array_values(array_filter($allViews,  fn(string $v) => $cfg->shouldIncludeView($v)));

        if (empty($tables) && empty($views)) {
            throw new \RuntimeException(
                "All tables and views were filtered out by include_tables / exclude_tables / " .
                "include_views / exclude_views. Found tables: " . implode(', ', $allTables) .
                ". Found views: " . implode(', ', $allViews)
            );
        }

        $viewCount  = count($views);
        $tableCount = count($tables);

        $lines = [];
        $lines[] = '-- -------------------------------------------------------------------------';
        $lines[] = '-- Schema generated by sqlc-php v' . Version::VERSION . ' --generate-schema';
        $lines[] = '-- Database : ' . $dbName;
        $lines[] = '-- Tables   : ' . $tableCount . ' (of ' . count($allTables) . ' total)';
        if (!empty($allViews)) {
            $lines[] = '-- Views    : ' . $viewCount . ' (of ' . count($allViews) . ' total)';
        }
        $lines[] = '-- Generated: ' . date('Y-m-d H:i:s');
        $lines[] = '--';
        $lines[] = '-- Do not edit manually — regenerate with: sqlc-php --generate-schema';
        $lines[] = '-- -------------------------------------------------------------------------';
        $lines[] = '';

        // ── Tables ────────────────────────────────────────────────────────────
        if (!empty($tables)) {
            foreach ($tables as $tableName) {
                $ddl = $this->showCreateTable($pdo, $tableName);
                $ddl = $this->cleanTableDdl($ddl);
                $lines[] = $ddl . ';';
                $lines[] = '';
            }
        }

        // ── Views ─────────────────────────────────────────────────────────────
        if (!empty($views)) {
            $lines[] = '-- ── Views ──────────────────────────────────────────────────────────────';
            $lines[] = '';

            foreach ($views as $viewName) {
                $ddl = $this->showCreateView($pdo, $viewName);
                $ddl = $this->cleanViewDdl($ddl);
                $lines[] = $ddl . ';';
                $lines[] = '';
            }
        }

        return implode("\n", $lines);
    }

    // -------------------------------------------------------------------------

    /**
     * List all tables and views in the current database, separated by type.
     *
     * Uses SHOW FULL TABLES which returns two columns:
     *   Tables_in_{db}  |  Table_type  (BASE TABLE | VIEW)
     *
     * @return array{tables: string[], views: string[]}
     */
    private function listObjects(\PDO $pdo): array
    {
        $stmt = $pdo->query('SHOW FULL TABLES');
        if ($stmt === false) {
            throw new \RuntimeException('SHOW FULL TABLES failed — check database permissions.');
        }

        $tables = [];
        $views  = [];

        foreach ($stmt->fetchAll(\PDO::FETCH_NUM) as $row) {
            $name = (string) $row[0];
            $type = (string) ($row[1] ?? 'BASE TABLE');

            if (strtoupper($type) === 'VIEW') {
                $views[] = $name;
            } else {
                $tables[] = $name;
            }
        }

        return ['tables' => $tables, 'views' => $views];
    }

    private function showCreateTable(\PDO $pdo, string $tableName): string
    {
        $safe = '`' . str_replace('`', '``', $tableName) . '`';
        $stmt = $pdo->query("SHOW CREATE TABLE {$safe}");

        if ($stmt === false) {
            throw new \RuntimeException("SHOW CREATE TABLE failed for table '{$tableName}'.");
        }

        $row = $stmt->fetch(\PDO::FETCH_ASSOC);
        if ($row === false) {
            throw new \RuntimeException("Empty result from SHOW CREATE TABLE '{$tableName}'.");
        }

        return $row['Create Table'] ?? array_values($row)[1] ?? '';
    }

    private function showCreateView(\PDO $pdo, string $viewName): string
    {
        $safe = '`' . str_replace('`', '``', $viewName) . '`';
        $stmt = $pdo->query("SHOW CREATE VIEW {$safe}");

        if ($stmt === false) {
            throw new \RuntimeException("SHOW CREATE VIEW failed for view '{$viewName}'.");
        }

        $row = $stmt->fetch(\PDO::FETCH_ASSOC);
        if ($row === false) {
            throw new \RuntimeException("Empty result from SHOW CREATE VIEW '{$viewName}'.");
        }

        // SHOW CREATE VIEW returns: View | Create View | character_set_client | collation_connection
        return $row['Create View'] ?? array_values($row)[1] ?? '';
    }

    /**
     * Post-process CREATE TABLE DDL.
     * Removes values that change between dumps and create spurious git diffs.
     */
    private function cleanTableDdl(string $ddl): string
    {
        // Remove AUTO_INCREMENT=<n> from table options
        $ddl = preg_replace('/\s+AUTO_INCREMENT=\d+/i', '', $ddl) ?? $ddl;

        return rtrim($ddl);
    }

    /**
     * @deprecated renamed to cleanTableDdl — kept for backward compatibility with tests
     */
    private function cleanDdl(string $ddl): string
    {
        return $this->cleanTableDdl($ddl);
    }

    /**
     * Post-process CREATE VIEW DDL.
     *
     * MySQL includes several clauses that are irrelevant for PHP type generation
     * and cause noisy git diffs. We strip them and normalize to a clean
     * CREATE OR REPLACE VIEW form that SchemaParser can consume.
     *
     * Stripped:
     *   - ALGORITHM={UNDEFINED|MERGE|TEMPTABLE}
     *   - DEFINER=`user`@`host`
     *   - SQL SECURITY {DEFINER|INVOKER}
     *
     * Example raw:
     *   CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER
     *   VIEW `reserve_assignment_active` AS SELECT ...
     *
     * Normalized:
     *   CREATE OR REPLACE VIEW `reserve_assignment_active` AS SELECT ...
     */
    private function cleanViewDdl(string $ddl): string
    {
        // Strip ALGORITHM=...
        $ddl = preg_replace('/\bALGORITHM\s*=\s*\w+\s*/i', '', $ddl) ?? $ddl;

        // Strip DEFINER=`user`@`host` or DEFINER='user'@'host'
        $ddl = preg_replace('/\bDEFINER\s*=\s*[`\']?\w[^@]*[`\']?@[`\']?[^`\'\s]+[`\']?\s*/i', '', $ddl) ?? $ddl;

        // Strip SQL SECURITY DEFINER|INVOKER
        $ddl = preg_replace('/\bSQL\s+SECURITY\s+\w+\s*/i', '', $ddl) ?? $ddl;

        // Normalize CREATE VIEW → CREATE OR REPLACE VIEW (idempotent on reimport)
        $ddl = preg_replace('/\bCREATE\s+VIEW\b/i', 'CREATE OR REPLACE VIEW', $ddl) ?? $ddl;

        // Collapse multiple spaces that stripping may have left
        $ddl = preg_replace('/  +/', ' ', $ddl) ?? $ddl;

        return rtrim($ddl);
    }
}
