<?php

declare(strict_types=1);

namespace SqlcPhp\Criteria;

/**
 * Fluent, immutable criteria builder for dynamic WHERE conditions.
 *
 * Generated {Group}Criteria classes extend this class and add typed
 * per-column methods (whereActiveEq, whereEmailLike, etc.) plus an
 * ALLOWED_COLUMNS whitelist to prevent SQL injection.
 *
 * This base class provides the SQL-building and PDO-binding machinery.
 * It can also be used directly with the add() method for ad-hoc filters.
 *
 * Usage (via generated subclass):
 *   $criteria = (new UserCriteria())
 *       ->whereActiveIn(1, 2)
 *       ->whereEmailLike('cristian')
 *       ->orderByCreatedAt('DESC');
 *
 * Usage (via base class):
 *   $criteria = (new Criteria())
 *       ->add(Filter::eq('active', 1))
 *       ->add(Filter::in('country_id', [164, 165]));
 */
class Criteria
{
    /** @var Filter[] */
    protected array $filters = [];

    protected ?string $orderByColumn = null;
    protected string  $orderByDir    = 'ASC';

    /**
     * Columns that may be used in orderBy().
     * Subclasses override this with the actual schema columns.
     * An empty array means all order-by columns are refused.
     *
     * @var string[]
     */
    protected array $allowedColumns = [];

    // -------------------------------------------------------------------------
    // Filter accumulation
    // -------------------------------------------------------------------------

    /**
     * Add a filter condition. Returns a new instance (immutable pattern).
     */
    public function add(Filter $filter): static
    {
        $clone          = clone $this;
        $clone->filters = [...$this->filters, $filter];
        return $clone;
    }

    /**
     * Set ORDER BY. Returns a new instance.
     *
     * @throws \InvalidArgumentException if column is not in the allowed list
     */
    public function orderBy(string $column, string $direction = 'ASC'): static
    {
        if (!empty($this->allowedColumns) && !in_array($column, $this->allowedColumns, true)) {
            throw new \InvalidArgumentException(
                "Column '{$column}' is not allowed for ordering. " .
                "Allowed: " . implode(', ', $this->allowedColumns)
            );
        }

        $clone              = clone $this;
        $clone->orderByColumn = $column;
        $clone->orderByDir    = strtoupper($direction) === 'DESC' ? 'DESC' : 'ASC';
        return $clone;
    }

    public function isEmpty(): bool
    {
        return empty($this->filters) && $this->orderByColumn === null;
    }

    public function hasFilters(): bool
    {
        return !empty($this->filters);
    }

    public function hasOrderBy(): bool
    {
        return $this->orderByColumn !== null;
    }

    // -------------------------------------------------------------------------
    // SQL generation
    // -------------------------------------------------------------------------

    /**
     * Build the WHERE or AND clause for this criteria.
     *
     * @param bool $appendMode  When true, emits " AND cond1 AND cond2".
     *                          When false, emits " WHERE cond1 AND cond2".
     */
    public function toFilterClause(bool $appendMode = false): string
    {
        if (empty($this->filters)) return '';

        $parts = [];
        $idx   = 0;

        foreach ($this->filters as $filter) {
            $parts[] = $this->renderCondition($filter, $idx);
            $idx++;
        }

        $keyword = $appendMode ? ' AND ' : ' WHERE ';
        return $keyword . implode(' AND ', $parts);
    }

    /**
     * Alias for toFilterClause(appendMode: false).
     */
    public function toWhereClause(): string
    {
        return $this->toFilterClause(false);
    }

    /**
     * Build the ORDER BY clause. Returns '' when no order is set.
     * Does NOT strip an existing ORDER BY from the base SQL — the caller must do that.
     */
    public function toOrderClause(): string
    {
        if ($this->orderByColumn === null) return '';
        return " ORDER BY {$this->orderByColumn} {$this->orderByDir}";
    }

    /**
     * Return all filter bindings as an associative array.
     * Matches the placeholder names generated by toFilterClause().
     *
     * Used internally by bindAll() and externally by QueryObject construction.
     *
     * @return array<string, array{0: mixed, 1: int}>  placeholder → [value, PDO type]
     */
    public function getBindings(): array
    {
        $result = [];
        $idx    = 0;

        foreach ($this->filters as $filter) {
            if ($filter->operator->isNoValue()) {
                $idx++;
                continue;
            }

            $base = $this->paramBase($filter->column, $idx);

            if ($filter->operator->isMultiValue()) {
                $values = is_array($filter->value) ? $filter->value : [$filter->value];
                foreach ($values as $i => $v) {
                    $result[":{$base}_{$i}"] = [$v, $this->pdoType($v)];
                }
            } elseif ($filter->operator->isTwoValue()) {
                $result[":{$base}_from"] = [$filter->value,   $this->pdoType($filter->value)];
                $result[":{$base}_to"]   = [$filter->valueTo, $this->pdoType($filter->valueTo)];
            } elseif ($filter->operator === FilterOperator::LIKE
                   || $filter->operator === FilterOperator::STARTS
                   || $filter->operator === FilterOperator::ENDS) {
                $result[":{$base}"] = [$filter->value, \PDO::PARAM_STR];
            } else {
                $result[":{$base}"] = [$filter->value, $this->pdoType($filter->value)];
            }

            $idx++;
        }

        return $result;
    }

    /**
     * Bind all filter values to a prepared statement.
     * Matches the placeholder names generated by toFilterClause().
     */
    public function bindAll(\PDOStatement $stmt): void
    {
        foreach ($this->getBindings() as $key => [$value, $type]) {
            $stmt->bindValue($key, $value, $type);
        }
    }

    // -------------------------------------------------------------------------
    // Internal helpers
    // -------------------------------------------------------------------------

    private function renderCondition(Filter $filter, int $idx): string
    {
        $col  = $filter->column;
        $op   = $filter->operator;
        $base = $this->paramBase($col, $idx);

        return match (true) {
            $op->isNoValue() => "{$col} {$op->value}",

            $op->isMultiValue() => (function () use ($filter, $op, $col, $base): string {
                $values = is_array($filter->value) ? $filter->value : [$filter->value];
                if (empty($values)) {
                    // Degenerate case: IN() with no values → always-false condition
                    return $op === FilterOperator::IN ? '(1 = 0)' : '(1 = 1)';
                }
                $placeholders = implode(', ', array_map(fn($i) => ":{$base}_{$i}", array_keys($values)));
                return "{$col} {$op->value} ({$placeholders})";
            })(),

            $op->isTwoValue() =>
                "{$col} BETWEEN :{$base}_from AND :{$base}_to",

            $op === FilterOperator::LIKE,
            $op === FilterOperator::STARTS,
            $op === FilterOperator::ENDS =>
                "{$col} LIKE :{$base}",

            default => "{$col} {$op->value} :{$base}",
        };
    }

    /**
     * Generate a unique, safe placeholder name for a filter.
     * Format: {sanitized_column}_f{idx}
     * Example: country_id → country_id_f0, country_id_f1, ...
     */
    private function paramBase(string $column, int $idx): string
    {
        // Strip table prefix (users.email → email) and sanitize
        $col = preg_replace('/[^a-zA-Z0-9_]/', '_', $column);
        $col = ltrim($col, '_');
        return "{$col}_f{$idx}";
    }

    private function pdoType(mixed $value): int
    {
        return match (true) {
            is_int($value)  => \PDO::PARAM_INT,
            is_bool($value) => \PDO::PARAM_BOOL,
            is_null($value) => \PDO::PARAM_NULL,
            default         => \PDO::PARAM_STR,
        };
    }
}
