<?php

declare(strict_types=1);

namespace SqlcPhp\Tests;

use PHPUnit\Framework\TestCase;
use SqlcPhp\Analyzer\QueryAnalyzer;
use SqlcPhp\Catalog\SchemaCatalog;
use SqlcPhp\Generator\EnumGenerator;
use SqlcPhp\Generator\ExtensionGenerator;
use SqlcPhp\Generator\JsonDtoGenerator;
use SqlcPhp\Generator\ResultDtoGenerator;
use SqlcPhp\Parser\QueryParser;
use SqlcPhp\Parser\SchemaParser;
use SqlcPhp\Resolver\ColumnResolver;
use SqlcPhp\Resolver\ExpressionTypeResolver;
use SqlcPhp\Resolver\ParamResolver;
use SqlcPhp\Rewriter\SqlRewriter;
use SqlcPhp\TypeMapper\MySQLTypeMapper;

/**
 * Tests for the @json annotation feature.
 *
 * @json alias ClassName declares that a JSON_ARRAYAGG column should be
 * deserialized into a typed DTO array instead of a plain PHP array.
 *
 * The DTO class is always generated by sqlc-php, resolved against the schema
 * table whose name matches the class (City → cities, Country → countries, etc.).
 * Placement respects scoped_dtos: true/false.
 */
class JsonAnnotationTest extends TestCase
{
    private SchemaCatalog      $catalog;
    private MySQLTypeMapper    $mapper;
    private QueryParser        $parser;
    private QueryAnalyzer      $analyzer;
    private ResultDtoGenerator $dtoGen;
    private ResultDtoGenerator $scopedDtoGen;
    private ExtensionGenerator $extGen;

    protected function setUp(): void
    {
        $schema = <<<SQL
            CREATE TABLE countries (
                id   INT          AUTO_INCREMENT PRIMARY KEY,
                name VARCHAR(100) NOT NULL,
                code CHAR(2)      NOT NULL
            );
            CREATE TABLE cities (
                id         INT          AUTO_INCREMENT PRIMARY KEY,
                name       VARCHAR(100) NOT NULL,
                slug       VARCHAR(100) NOT NULL,
                country_id INT          NOT NULL
            );
            CREATE TABLE products (
                id    INT          AUTO_INCREMENT PRIMARY KEY,
                name  VARCHAR(200) NOT NULL,
                price DECIMAL(10,2) NOT NULL,
                sku   VARCHAR(50)   NOT NULL
            );
        SQL;

        $this->catalog      = new SchemaCatalog((new SchemaParser())->parse($schema));
        $this->mapper       = new MySQLTypeMapper([], new EnumGenerator('App'));
        $this->parser       = new QueryParser();
        $pr                 = new ParamResolver($this->catalog, $this->mapper);
        $er                 = new ExpressionTypeResolver($this->catalog, $this->mapper);
        $cr                 = new ColumnResolver($this->catalog, $this->mapper, $pr, $er);
        $this->analyzer     = new QueryAnalyzer($pr, $cr, $this->parser, new SqlRewriter(), $this->catalog);
        $this->dtoGen       = new ResultDtoGenerator('App\\DTOs', $this->mapper, $this->catalog);
        $this->scopedDtoGen = new ResultDtoGenerator('App\\DTOs', $this->mapper, $this->catalog);
        $this->extGen       = new ExtensionGenerator('App\\Extensions\\Models', 'App\\Extensions\\DTOs');
    }

    private function analyze(string $sql): array
    {
        return $this->analyzer->analyze($this->parser->parse($sql));
    }

    // =========================================================================
    // QueryParser — @json annotation parsing
    // =========================================================================

    public function test_parser_captures_single_json_annotation(): void
    {
        $queries = $this->parser->parse(<<<SQL
            -- @name GetCountryWithCities
            -- @class Country
            -- @returns :one
            -- @json cities City
            SELECT countries.id, countries.name,
                JSON_ARRAYAGG(JSON_OBJECT('id', cities.id, 'name', cities.name)) AS cities
            FROM countries
            INNER JOIN cities ON cities.country_id = countries.id
            WHERE countries.id = :id
            GROUP BY countries.id;
        SQL);

        $this->assertCount(1, $queries);
        $this->assertSame(['cities' => 'City'], $queries[0]->jsonColumns);
    }

    public function test_parser_captures_multiple_json_annotations(): void
    {
        $queries = $this->parser->parse(<<<SQL
            -- @name GetOrderFull
            -- @class Order
            -- @returns :one
            -- @json cities City
            -- @json products Product
            SELECT 1 AS id, '[]' AS cities, '[]' AS products;
        SQL);

        $this->assertSame(
            ['cities' => 'City', 'products' => 'Product'],
            $queries[0]->jsonColumns
        );
    }

    public function test_parser_json_columns_empty_when_no_annotation(): void
    {
        $queries = $this->parser->parse(<<<SQL
            -- @name ListCountries
            -- @class Country
            -- @returns :many
            SELECT countries.* FROM countries;
        SQL);

        $this->assertSame([], $queries[0]->jsonColumns);
    }

    // =========================================================================
    // JsonDtoGenerator — table resolution
    // =========================================================================

    public function test_json_dto_generator_resolves_plural_table(): void
    {
        $gen = new JsonDtoGenerator($this->catalog, $this->mapper);

        $this->assertSame('cities', $gen->resolveTableName('City'));
        $this->assertSame('countries', $gen->resolveTableName('Country'));
        $this->assertSame('products', $gen->resolveTableName('Product'));
    }

    public function test_json_dto_generator_returns_null_for_unknown_class(): void
    {
        $gen = new JsonDtoGenerator($this->catalog, $this->mapper);

        $this->assertNull($gen->resolveTableName('Invoice'));
        $this->assertNull($gen->resolveTableName('Warehouse'));
    }

    public function test_json_dto_generator_produces_readonly_class(): void
    {
        $gen  = new JsonDtoGenerator($this->catalog, $this->mapper);
        $data = $gen->generate('City', 'App\\DTOs', 'cities');

        $this->assertSame('City', $data['className']);
        $this->assertStringContainsString('readonly class City', $data['code']);
        $this->assertStringContainsString('namespace App\\DTOs;', $data['code']);
    }

    public function test_json_dto_has_correct_properties_from_schema(): void
    {
        $gen  = new JsonDtoGenerator($this->catalog, $this->mapper);
        $data = $gen->generate('City', 'App\\DTOs', 'cities');

        $code = $data['code'];
        $this->assertStringContainsString('public int $id,', $code);
        $this->assertStringContainsString('public string $name,', $code);
        $this->assertStringContainsString('public string $slug,', $code);
        $this->assertStringContainsString('public int $country_id,', $code);
    }

    public function test_json_dto_has_from_row_method(): void
    {
        $gen  = new JsonDtoGenerator($this->catalog, $this->mapper);
        $data = $gen->generate('City', 'App\\DTOs', 'cities');

        $code = $data['code'];
        $this->assertStringContainsString('public static function fromRow(array $row): self', $code);
        $this->assertStringContainsString("(int) \$row['id']", $code);
        $this->assertStringContainsString("(string) \$row['name']", $code);
        $this->assertStringContainsString("(string) \$row['slug']", $code);
    }

    public function test_json_dto_throws_for_unknown_table(): void
    {
        $gen = new JsonDtoGenerator($this->catalog, $this->mapper);

        $this->expectException(\RuntimeException::class);
        $this->expectExceptionMessageMatches('/@json.*Invoice.*no matching table/');
        $gen->generate('Invoice', 'App\\DTOs', 'invoices');
    }

    // =========================================================================
    // ResultDtoGenerator — @json columns in parent DTO
    // =========================================================================

    public function test_result_dto_uses_array_type_for_json_column(): void
    {
        $queries = $this->analyze(<<<SQL
            -- @name GetCountryWithCities
            -- @class Country
            -- @returns :one
            -- @json cities City
            SELECT
                countries.id,
                countries.name,
                JSON_ARRAYAGG(JSON_OBJECT('id', cities.id)) AS cities
            FROM countries
            INNER JOIN cities ON cities.country_id = countries.id
            WHERE countries.id = :id
            GROUP BY countries.id;
        SQL);

        $r = $this->dtoGen->generate($queries[0]);

        // Parent DTO declares array type (plain PHP for the property)
        $this->assertStringContainsString('public array $cities,', $r['code']);
    }

    public function test_result_dto_uses_array_map_cast_for_json_column(): void
    {
        $queries = $this->analyze(<<<SQL
            -- @name GetCountryWithCities
            -- @class Country
            -- @returns :one
            -- @json cities City
            SELECT
                countries.id,
                countries.name,
                JSON_ARRAYAGG(JSON_OBJECT('id', cities.id)) AS cities
            FROM countries
            INNER JOIN cities ON cities.country_id = countries.id
            WHERE countries.id = :id
            GROUP BY countries.id;
        SQL);

        $r = $this->dtoGen->generate($queries[0]);

        // fromRow uses array_map with City::fromRow
        $this->assertStringContainsString('array_map(fn(array $r) => City::fromRow($r)', $r['code']);
        $this->assertStringContainsString("json_decode((string) \$row['cities'], true) ?? []", $r['code']);
    }

    public function test_result_dto_has_docblock_for_json_column(): void
    {
        $queries = $this->analyze(<<<SQL
            -- @name GetCountryWithCities
            -- @class Country
            -- @returns :one
            -- @json cities City
            SELECT
                countries.id,
                countries.name,
                JSON_ARRAYAGG(JSON_OBJECT('id', cities.id)) AS cities
            FROM countries
            INNER JOIN cities ON cities.country_id = countries.id
            WHERE countries.id = :id
            GROUP BY countries.id;
        SQL);

        $r = $this->dtoGen->generate($queries[0]);

        // @var docblock for IDE type hinting
        $this->assertStringContainsString('@var City[]', $r['code']);
    }

    public function test_result_dto_generates_json_dto_file(): void
    {
        $queries = $this->analyze(<<<SQL
            -- @name GetCountryWithCities
            -- @class Country
            -- @returns :one
            -- @json cities City
            SELECT
                countries.id,
                countries.name,
                JSON_ARRAYAGG(JSON_OBJECT('id', cities.id)) AS cities
            FROM countries
            INNER JOIN cities ON cities.country_id = countries.id
            WHERE countries.id = :id
            GROUP BY countries.id;
        SQL);

        $r = $this->dtoGen->generate($queries[0]);

        $this->assertArrayHasKey('jsonDtos', $r);
        $this->assertArrayHasKey('City', $r['jsonDtos']);
        $this->assertSame('City', $r['jsonDtos']['City']['className']);
        $this->assertStringContainsString('readonly class City', $r['jsonDtos']['City']['code']);
    }

    public function test_result_dto_generates_multiple_json_dto_files(): void
    {
        $queries = $this->analyze(<<<SQL
            -- @name GetCountryFull
            -- @class Country
            -- @returns :one
            -- @json cities City
            -- @json products Product
            SELECT
                countries.id,
                countries.name,
                JSON_ARRAYAGG(JSON_OBJECT('id', cities.id)) AS cities,
                JSON_ARRAYAGG(JSON_OBJECT('id', products.id)) AS products
            FROM countries
            INNER JOIN cities ON cities.country_id = countries.id
            INNER JOIN products ON products.id = 1
            WHERE countries.id = :id
            GROUP BY countries.id;
        SQL);

        $r = $this->dtoGen->generate($queries[0]);

        $this->assertCount(2, $r['jsonDtos']);
        $this->assertArrayHasKey('City', $r['jsonDtos']);
        $this->assertArrayHasKey('Product', $r['jsonDtos']);
    }

    public function test_result_dto_throws_when_json_class_has_no_matching_table(): void
    {
        $queries = $this->analyze(<<<SQL
            -- @name GetWithInvoices
            -- @class Country
            -- @returns :one
            -- @json invoices Invoice
            SELECT countries.id, JSON_ARRAYAGG(1) AS invoices
            FROM countries
            WHERE countries.id = :id;
        SQL);

        $this->expectException(\RuntimeException::class);
        $this->expectExceptionMessageMatches("/Invoice.*no matching table/");
        $this->dtoGen->generate($queries[0]);
    }

    // =========================================================================
    // scoped_dtos: false — JSON DTOs placed flat
    // =========================================================================

    public function test_json_dtos_returned_for_non_scoped_writes(): void
    {
        $queries = $this->analyze(<<<SQL
            -- @name GetCountryWithCities
            -- @class Country
            -- @returns :one
            -- @json cities City
            SELECT
                countries.id,
                countries.name,
                JSON_ARRAYAGG(JSON_OBJECT('id', cities.id)) AS cities
            FROM countries
            INNER JOIN cities ON cities.country_id = countries.id
            WHERE countries.id = :id
            GROUP BY countries.id;
        SQL);

        $r = $this->dtoGen->generate($queries[0], false);

        // scoped=false: no scopeSubdir, but jsonDtos still populated
        $this->assertNull($r['scopeSubdir']);
        $this->assertNotEmpty($r['jsonDtos']);
    }

    // =========================================================================
    // scoped_dtos: true — JSON DTOs placed in scoped subdirectory
    // =========================================================================

    public function test_json_dtos_scoped_when_scoped_dtos_enabled(): void
    {
        $queries = $this->analyze(<<<SQL
            -- @name GetCountryWithCities
            -- @class Country
            -- @returns :one
            -- @json cities City
            SELECT
                countries.id,
                countries.name,
                JSON_ARRAYAGG(JSON_OBJECT('id', cities.id)) AS cities
            FROM countries
            INNER JOIN cities ON cities.country_id = countries.id
            WHERE countries.id = :id
            GROUP BY countries.id;
        SQL);

        $r = $this->scopedDtoGen->generate($queries[0], true);

        // When scoped, the scopeSubdir is set — the CLI uses it to place JSON DTOs
        $this->assertNotNull($r['scopeSubdir']);
        $this->assertSame('Country/GetCountryWithCities', $r['scopeSubdir']);
        $this->assertArrayHasKey('City', $r['jsonDtos']);
    }

    public function test_json_dto_namespace_uses_scoped_namespace_when_scoped(): void
    {
        $queries = $this->analyze(<<<SQL
            -- @name GetCountryWithCities
            -- @class Country
            -- @returns :one
            -- @json cities City
            SELECT
                countries.id,
                countries.name,
                JSON_ARRAYAGG(JSON_OBJECT('id', cities.id)) AS cities
            FROM countries
            INNER JOIN cities ON cities.country_id = countries.id
            WHERE countries.id = :id
            GROUP BY countries.id;
        SQL);

        $r = $this->scopedDtoGen->generate($queries[0], true);

        // The City DTO must declare the scoped namespace so it can be found
        $this->assertStringContainsString(
            'namespace App\\DTOs\\Country\\GetCountryWithCities;',
            $r['jsonDtos']['City']['code']
        );
    }

    // =========================================================================
    // Non-@json columns are unaffected
    // =========================================================================

    public function test_non_json_columns_use_normal_cast(): void
    {
        $queries = $this->analyze(<<<SQL
            -- @name GetCountryWithCities
            -- @class Country
            -- @returns :one
            -- @json cities City
            SELECT
                countries.id,
                countries.name,
                JSON_ARRAYAGG(JSON_OBJECT('id', cities.id)) AS cities
            FROM countries
            INNER JOIN cities ON cities.country_id = countries.id
            WHERE countries.id = :id
            GROUP BY countries.id;
        SQL);

        $r = $this->dtoGen->generate($queries[0]);

        // id and name use normal casts, not array_map
        $this->assertStringContainsString("(int) \$row['id']", $r['code']);
        $this->assertStringContainsString("(string) \$row['name']", $r['code']);
    }

    public function test_query_without_json_annotation_has_empty_json_dtos(): void
    {
        $queries = $this->analyze(<<<SQL
            -- @name GetCountryWithRole
            -- @class Country
            -- @returns :one
            SELECT countries.id, countries.name, countries.code
            FROM countries
            WHERE countries.id = :id;
        SQL);

        $r = $this->dtoGen->generate($queries[0]);

        $this->assertArrayHasKey('jsonDtos', $r);
        $this->assertEmpty($r['jsonDtos']);
    }

    // =========================================================================
    // Extensions — @json DTO gets its own extension trait
    // =========================================================================

    public function test_json_dto_extension_is_generated_when_extgen_provided(): void
    {
        $queries = $this->analyze(<<<SQL
            -- @name GetCountryWithCities
            -- @class Country
            -- @returns :one
            -- @json cities City
            SELECT
                countries.id,
                countries.name,
                JSON_ARRAYAGG(JSON_OBJECT('id', cities.id)) AS cities
            FROM countries
            INNER JOIN cities ON cities.country_id = countries.id
            WHERE countries.id = :id
            GROUP BY countries.id;
        SQL);

        $r = $this->dtoGen->generate($queries[0], false, $this->extGen);

        // Extension for City JSON DTO must exist
        $this->assertNotEmpty($r['extensions']);
        $extKeys = array_keys($r['extensions']);
        $cityExtKey = array_filter($extKeys, fn($k) => str_contains($k, 'City'));
        $this->assertNotEmpty($cityExtKey, 'CityExtension not found in extensions');
    }

    public function test_json_dto_extension_has_correct_trait_name(): void
    {
        $queries = $this->analyze(<<<SQL
            -- @name GetCountryWithCities
            -- @class Country
            -- @returns :one
            -- @json cities City
            SELECT
                countries.id,
                countries.name,
                JSON_ARRAYAGG(JSON_OBJECT('id', cities.id)) AS cities
            FROM countries
            INNER JOIN cities ON cities.country_id = countries.id
            WHERE countries.id = :id
            GROUP BY countries.id;
        SQL);

        $r = $this->dtoGen->generate($queries[0], false, $this->extGen);

        $cityExt = null;
        foreach ($r['extensions'] as $ext) {
            if ($ext->traitName === 'CityExtension') {
                $cityExt = $ext;
                break;
            }
        }

        $this->assertNotNull($cityExt, 'CityExtension not found');
        $this->assertStringContainsString('trait CityExtension', $cityExt->scaffoldCode);
    }

    public function test_json_dto_extension_has_property_tags_from_schema(): void
    {
        $queries = $this->analyze(<<<SQL
            -- @name GetCountryWithCities
            -- @class Country
            -- @returns :one
            -- @json cities City
            SELECT
                countries.id,
                countries.name,
                JSON_ARRAYAGG(JSON_OBJECT('id', cities.id)) AS cities
            FROM countries
            INNER JOIN cities ON cities.country_id = countries.id
            WHERE countries.id = :id
            GROUP BY countries.id;
        SQL);

        $r = $this->dtoGen->generate($queries[0], false, $this->extGen);

        $cityExt = null;
        foreach ($r['extensions'] as $ext) {
            if ($ext->traitName === 'CityExtension') { $cityExt = $ext; break; }
        }

        $this->assertNotNull($cityExt);
        // Extension scaffold should list City's schema columns as @property
        $this->assertStringContainsString('@property int    $id', $cityExt->scaffoldCode);
        $this->assertStringContainsString('@property string $name', $cityExt->scaffoldCode);
        $this->assertStringContainsString('@property string $slug', $cityExt->scaffoldCode);
    }

    public function test_json_dto_code_has_use_extension_injected(): void
    {
        $queries = $this->analyze(<<<SQL
            -- @name GetCountryWithCities
            -- @class Country
            -- @returns :one
            -- @json cities City
            SELECT
                countries.id,
                countries.name,
                JSON_ARRAYAGG(JSON_OBJECT('id', cities.id)) AS cities
            FROM countries
            INNER JOIN cities ON cities.country_id = countries.id
            WHERE countries.id = :id
            GROUP BY countries.id;
        SQL);

        $r = $this->dtoGen->generate($queries[0], false, $this->extGen);

        // The generated City.php code should have the extension trait injected
        $this->assertArrayHasKey('City', $r['jsonDtos']);
        $cityCode = $r['jsonDtos']['City']['code'];
        $this->assertStringContainsString('use CityExtension;', $cityCode);
    }

    public function test_main_dto_extension_includes_json_column_as_array_property(): void
    {
        $queries = $this->analyze(<<<SQL
            -- @name GetCountryWithCities
            -- @class Country
            -- @returns :one
            -- @json cities City
            SELECT
                countries.id,
                countries.name,
                JSON_ARRAYAGG(JSON_OBJECT('id', cities.id)) AS cities
            FROM countries
            INNER JOIN cities ON cities.country_id = countries.id
            WHERE countries.id = :id
            GROUP BY countries.id;
        SQL);

        $r = $this->dtoGen->generate($queries[0], false, $this->extGen);

        // The parent DTO extension should list `cities` as @property array
        $parentExt = null;
        foreach ($r['extensions'] as $ext) {
            if ($ext->traitName === 'GetCountryWithCitiesRowExtension') {
                $parentExt = $ext;
                break;
            }
        }

        $this->assertNotNull($parentExt, 'Parent DTO extension not found');
        // Extension scaffold should list `cities` as @property array
        $this->assertMatchesRegularExpression('/@property array\s+\$cities/', $parentExt->scaffoldCode);
    }

    public function test_json_dto_extension_scoped_when_scoped_dtos_enabled(): void
    {
        $queries = $this->analyze(<<<SQL
            -- @name GetCountryWithCities
            -- @class Country
            -- @returns :one
            -- @json cities City
            SELECT
                countries.id,
                countries.name,
                JSON_ARRAYAGG(JSON_OBJECT('id', cities.id)) AS cities
            FROM countries
            INNER JOIN cities ON cities.country_id = countries.id
            WHERE countries.id = :id
            GROUP BY countries.id;
        SQL);

        $r = $this->scopedDtoGen->generate($queries[0], true, $this->extGen);

        $cityExt = null;
        foreach ($r['extensions'] as $key => $ext) {
            if ($ext->traitName === 'CityExtension') { $cityExt = $ext; break; }
        }

        $this->assertNotNull($cityExt, 'CityExtension not found in scoped mode');
        // Scoped extension must include the subdirectory in its relPath
        $this->assertStringContainsString('Country', $cityExt->relPath);
        $this->assertStringContainsString('GetCountryWithCities', $cityExt->relPath);
    }
}
