<?php

declare(strict_types=1);

namespace SqlcPhp\Generator;

use SqlcPhp\Parser\EmbedDefinition;
use SqlcPhp\Resolver\ResolvedColumn;
use SqlcPhp\TypeMapper\TypeMapperInterface;

/**
 * Generates the nested value-object class for an @embed group.
 *
 * Given:
 *   -- @embed Role role_
 *   with columns: role_name (string), role_description (?string)
 *
 * Produces:
 *   readonly class Role {
 *       public function __construct(
 *           public string  $name,
 *           public ?string $description,
 *       ) {}
 *       public static function fromRow(array $row): self { ... }
 *   }
 *
 * The class is emitted as an inner section of the parent *Row DTO file
 * (or as a standalone file if the same class is reused across queries).
 */
class EmbedGenerator
{
    public function __construct(
        private readonly string               $namespace,
        private readonly ?TypeMapperInterface $typeMapper = null,
    ) {}

    /**
     * Generate the PHP code for a single embedded value object.
     *
     * @param  EmbedDefinition   $embed   The @embed annotation
     * @param  ResolvedColumn[]  $columns All columns belonging to this embed group
     * @return array{className: string, code: string}
     */
    public function generate(EmbedDefinition $embed, array $columns): array
    {
        $className = $embed->className;
        $props     = [];
        $fromArgs  = [];

        foreach ($columns as $col) {
            // Strip the prefix to get the nested property name
            $propName   = $embed->stripPrefix($col->alias);
            $props[]    = "        public {$col->phpType} \${$propName},";
            $fromArgs[] = $this->buildCast($col->phpType, $col->alias, $col->nullable);
        }

        $propsStr    = implode("\n", $props);
        $fromArgsStr = implode("\n", $fromArgs);

        $code = <<<PHP
<?php

declare(strict_types=1);

namespace {$this->namespace};

/**
 * Embedded value object — generated by sqlc-php, do not edit manually.
 */
readonly class {$className}
{
    public function __construct(
{$propsStr}
    ) {}

    /**
     * Hydrate from a PDO result row (associative array).
     * Expects the original prefixed column names as keys.
     *
     * @param array<string, mixed> \$row
     */
    public static function fromRow(array \$row): self
    {
        return new self(
{$fromArgsStr}
        );
    }
}
PHP;

        return ['className' => $className, 'code' => $code];
    }

    private function buildCast(string $phpType, string $alias, bool $nullable): string
    {
        if ($this->typeMapper !== null) {
            $cast = $this->typeMapper->fromRowCast($phpType, $alias, $nullable);
            return "            {$cast},";
        }

        // Fallback when no mapper injected
        $base   = ltrim($phpType, '?\\');
        $access = "\$row['{$alias}']";

        if ($nullable) {
            return match($base) {
                'int'   => "            isset({$access}) ? (int) {$access} : null,",
                'float' => "            isset({$access}) ? (float) {$access} : null,",
                'bool'  => "            isset({$access}) ? (bool) {$access} : null,",
                'array' => "            isset({$access}) ? json_decode((string) {$access}, true) : null,",
                default => "            {$access} ?? null,",
            };
        }

        return match($base) {
            'int'   => "            (int) {$access},",
            'float' => "            (float) {$access},",
            'bool'  => "            (bool) {$access},",
            'array' => "            json_decode((string) {$access}, true) ?? [],",
            'mixed' => "            {$access},",
            default => "            (string) {$access},",
        };
    }
}
