<?php

declare(strict_types=1);

namespace SqlcPhp\Generator;

use SqlcPhp\Parser\ColumnDefinition;

/**
 * Generates a PHP 8.1 backed enum for a MySQL ENUM column.
 *
 * Example:
 *   Column: status ENUM('active', 'inactive', 'pending')
 *   Table:  users
 *
 * Generates:
 *   enum UserStatus: string {
 *       case Active   = 'active';
 *       case Inactive = 'inactive';
 *       case Pending  = 'pending';
 *   }
 *
 * Naming convention: {PascalTable}{PascalColumn}  → UserStatus
 */
class EnumGenerator
{
    public function __construct(
        private readonly string $namespace,
    ) {}

    /**
     * Generate the PHP enum class name for a given table + column.
     */
    public function enumClassName(string $tableName, string $columnName): string
    {
        return $this->toPascalCase($this->toSingular($tableName))
            . $this->toPascalCase($columnName);
    }

    /**
     * Generate a PHP backed enum file.
     *
     * @return array{className: string, code: string}
     */
    public function generate(string $tableName, ColumnDefinition $col): array
    {
        $className = $this->enumClassName($tableName, $col->name);
        $cases     = $this->buildCases($col->enumValues);

        $code = <<<PHP
<?php

declare(strict_types=1);

namespace {$this->namespace};

/**
 * PHP backed enum for `{$tableName}`.`{$col->name}`.
 * Generated by sqlc-php — do not edit manually.
 */
enum {$className}: string
{
{$cases}
}
PHP;

        return ['className' => $className, 'code' => $code];
    }

    private function buildCases(array $values): string
    {
        $lines = [];
        foreach ($values as $value) {
            $caseName = $this->toCaseName($value);
            $lines[]  = "    case {$caseName} = '{$value}';";
        }
        return implode("\n", $lines);
    }

    /**
     * Convert an enum value string to a valid PascalCase PHP enum case name.
     * e.g. "in-progress" → "InProgress", "type_a" → "TypeA"
     */
    private function toCaseName(string $value): string
    {
        // Split on non-alphanumeric characters
        $words = preg_split('/[^a-zA-Z0-9]+/', $value) ?: [$value];
        return implode('', array_map('ucfirst', array_map('strtolower', $words)));
    }

    private function toSingular(string $word): string
    {
        $word = strtolower($word);
        if (str_ends_with($word, 'ies')) return substr($word, 0, -3) . 'y';
        if (str_ends_with($word, 'ses') || str_ends_with($word, 'xes')) return substr($word, 0, -2);
        if (str_ends_with($word, 's') && !str_ends_with($word, 'ss')) return substr($word, 0, -1);
        return $word;
    }

    private function toPascalCase(string $word): string
    {
        return ucfirst(strtolower($word));
    }
}
