<?php

declare(strict_types=1);

namespace SqlcPhp\Generator;

use SqlcPhp\Parser\ColumnDefinition;

/**
 * Generates a PHP 8.1 backed enum for a MySQL ENUM column.
 *
 * Example:
 *   Column: status ENUM('active', 'inactive', 'pending')
 *   Table:  users
 *
 * Generates:
 *   enum UserStatus: string {
 *       case Active   = 'active';
 *       case Inactive = 'inactive';
 *       case Pending  = 'pending';
 *   }
 *
 * Naming convention: {PascalTable}{PascalColumn}  → UserStatus
 */
class EnumGenerator
{
    private \SqlcPhp\Inflector\InflectorService $inflector;

    public function __construct(
        private readonly string $namespace,
        string $language = 'english',
    ) {
        $this->inflector = new \SqlcPhp\Inflector\InflectorService($language);
    }

    /**
     * Generate the PHP enum class name for a given table + column.
     */
    public function enumClassName(string $tableName, string $columnName): string
    {
        return $this->inflector->toPascalCase($this->inflector->singularize($tableName))
            . $this->inflector->toPascalCase($columnName);
    }

    /**
     * Return the fully-qualified class name for an enum column.
     */
    public function enumFqcn(string $tableName, string $columnName): string
    {
        return $this->namespace . '\\' . $this->enumClassName($tableName, $columnName);
    }

    /**
     * Return the FQCN for an enum override where the class name is provided directly.
     * Used when enum_values is declared in type_overrides (VARCHAR-as-enum).
     */
    public function enumFqcnFromClass(string $className): string
    {
        return $this->namespace . '\\' . $className;
    }

    /**
     * Generate a PHP backed enum from an explicit list of values.
     * Used when enum_values is declared in type_overrides (VARCHAR-as-enum).
     *
     * @param  string   $className   The enum class name (from php_type)
     * @param  string[] $values      The allowed values (from enum_values)
     * @return array{className: string, code: string}
     */
    public function generateFromValues(string $className, array $values, ?ExtensionGenerator $extGen = null): array
    {
        $cases = $this->buildCases($values);

        $code = <<<PHP
<?php

declare(strict_types=1);

namespace {$this->namespace};

/**
 * PHP backed enum — declared via type_overrides enum_values.
 * Generated by sqlc-php — do not edit manually.
 */
enum {$className}: string
{
{$cases}
}
PHP;

        if ($extGen !== null) {
            $hostFqcn = $this->namespace . '\\' . $className;
            $caseDefs = array_map(
                fn(string $v) => ['name' => $this->toCaseName($v), 'value' => $v],
                $values
            );
            $ext  = $extGen->forEnum($className, $caseDefs, 'string', $hostFqcn);
            $code = $extGen->injectIntoEnum($code, $ext);
            return ['className' => $className, 'code' => $code, 'extension' => $ext];
        }

        return ['className' => $className, 'code' => $code];
    }

    /**
     * Generate a PHP backed enum file.
     *
     * When $extGen is provided, the generated enum will include a
     * `use XExtension;` statement and the scaffold will be returned
     * in the result array under 'extension'.
     *
     * @return array{className: string, code: string, extension?: ExtensionData}
     */
    public function generate(string $tableName, ColumnDefinition $col, ?ExtensionGenerator $extGen = null): array
    {
        $className = $this->enumClassName($tableName, $col->name);
        $cases     = $this->buildCases($col->enumValues);

        $code = <<<PHP
<?php

declare(strict_types=1);

namespace {$this->namespace};

/**
 * PHP backed enum for `{$tableName}`.`{$col->name}`.
 * Generated by sqlc-php — do not edit manually.
 */
enum {$className}: string
{
{$cases}
}
PHP;

        if ($extGen !== null) {
            $hostFqcn = $this->namespace . '\\' . $className;
            $caseDefs = array_map(
                fn(string $v) => ['name' => $this->toCaseName($v), 'value' => $v],
                $col->enumValues
            );
            $ext  = $extGen->forEnum($className, $caseDefs, 'string', $hostFqcn);
            $code = $extGen->injectIntoEnum($code, $ext);
            return ['className' => $className, 'code' => $code, 'extension' => $ext];
        }

        return ['className' => $className, 'code' => $code];
    }

    private function buildCases(array $values): string
    {
        $lines = [];
        foreach ($values as $value) {
            $caseName = $this->toCaseName($value);
            $lines[]  = "    case {$caseName} = '{$value}';";
        }
        return implode("\n", $lines);
    }

    /**
     * Convert an enum value string to a valid PascalCase PHP enum case name.
     * e.g. "in-progress" → "InProgress", "type_a" → "TypeA"
     */
    private function toCaseName(string $value): string
    {
        $words = preg_split('/[^a-zA-Z0-9]+/', $value) ?: [$value];
        return implode('', array_map('ucfirst', array_map('strtolower', $words)));
    }
}
