<?php

declare(strict_types=1);

namespace SqlcPhp\Generator;

use SqlcPhp\Parser\QueryDefinition;
use SqlcPhp\Parser\ReturnType;

/**
 * Generates a PHP interface for each Query class.
 *
 * The interface contains exactly the same method signatures as the
 * generated Query class, allowing consumers to depend on abstractions
 * rather than concrete PDO implementations.
 *
 * Naming convention: {Group}QueryInterface  e.g. UserQueryInterface
 *
 * Usage in Laravel:
 *   $this->app->bind(UserQueryInterface::class, fn($app) => new UserQuery(...));
 */
class InterfaceGenerator
{
    public function __construct(
        private readonly string $namespace,
    ) {}

    public function interfaceName(string $queryClassName): string
    {
        return $queryClassName . 'Interface';
    }

    /**
     * Generate the PHP interface file for a Query class.
     *
     * @param  string             $queryClassName  e.g. "UserQuery"
     * @param  QueryDefinition[]  $queries         All queries in this group
     * @param  QueryGenerator     $queryGen        Used to resolve return types and signatures
     * @return array{className: string, code: string}
     */
    public function generate(
        string         $queryClassName,
        array          $queries,
        QueryGenerator $queryGen,
    ): array {
        $interfaceName = $this->interfaceName($queryClassName);
        $methods       = [];

        foreach ($queries as $query) {
            $methods[] = $this->renderMethodSignature($query, $queryGen);
        }

        $methodsStr = implode("\n\n", $methods);

        $code = <<<PHP
<?php

declare(strict_types=1);

namespace {$this->namespace};

use PDO;

/**
 * Interface for `{$queryClassName}`.
 * Generated by sqlc-php — do not edit manually.
 */
interface {$interfaceName}
{
{$methodsStr}
}
PHP;

        return ['className' => $interfaceName, 'code' => $code];
    }

    private function renderMethodSignature(QueryDefinition $query, QueryGenerator $queryGen): string
    {
        $returnType = $queryGen->resolveReturnTypePublic($query);
        $paramList  = $queryGen->buildParamListPublic($query);

        // :many-paginated adds limit/offset at the end — nullable $limit
        if ($query->returns->value === ':many-paginated') {
            $sep       = $paramList !== '' ? ', ' : '';
            $paramList = $paramList . $sep . '?int $limit = null, int $offset = 0';
        }

        $docblock = $this->buildDocblock($query, $queryGen);

        $main = <<<PHP
{$docblock}
    public function {$query->name}({$paramList}): {$returnType};
PHP;

        // @counted: emit companion {name}Count() signature in the interface
        if ($query->counted && $query->returns->value === ':many-paginated') {
            $countParamList = $queryGen->buildParamListPublic($query); // no limit/offset
            $countName      = $query->name . 'Count';
            $main .= <<<PHP


    /**
     * Returns the total number of rows matching the filter conditions (without pagination).
     * @return int
     */
    public function {$countName}({$countParamList}): int;
PHP;
        }

        return $main;
    }

    private function buildDocblock(QueryDefinition $query, QueryGenerator $queryGen): string
    {
        $returnType = $queryGen->resolveReturnTypePublic($query);
        $lines      = ['    /**'];

        foreach ($query->params as $param) {
            $type    = $param->optional
                ? (str_starts_with($param->phpType, '?') ? $param->phpType : '?' . $param->phpType)
                : $param->phpType;
            $note    = $param->optional ? ' Pass null to skip this filter.' : '';
            $lines[] = "     * @param {$type} \${$param->name}{$note}";
        }

        $lines[] = match($query->returns->value) {
            ':exec'  => '     * @return void',
            default  => "     * @return {$returnType}",
        };

        $lines[] = '     */';
        return implode("\n", $lines);
    }
}
