<?php

declare(strict_types=1);

namespace SqlcPhp\Generator;

use SqlcPhp\Parser\QueryDefinition;
use SqlcPhp\Parser\ReturnType;

/**
 * Generates a PHP interface for each Query class.
 *
 * Method signatures are built via a strategy dispatch table: each return-type
 * family has a dedicated renderer. Adding a new return type means adding one
 * private method and one entry in the dispatch table — the main router never
 * changes.
 *
 * Naming convention: {Group}QueryInterface  e.g. UserQueryInterface
 */
class InterfaceGenerator
{
    public function __construct(
        private readonly string $namespace,
    ) {}

    public function interfaceName(string $queryClassName): string
    {
        return $queryClassName . 'Interface';
    }

    /**
     * Generate the PHP interface file for a Query class.
     *
     * @param  string             $queryClassName  e.g. "UserQuery"
     * @param  QueryDefinition[]  $queries         All queries in this group
     * @param  QueryGenerator     $queryGen        Used to resolve return types and signatures
     * @return array{className: string, code: string}
     */
    public function generate(
        string         $queryClassName,
        array          $queries,
        QueryGenerator $queryGen,
    ): array {
        $interfaceName = $this->interfaceName($queryClassName);
        $methods       = [];

        foreach ($queries as $query) {
            $methods[] = $this->renderMethodSignature($query, $queryGen);
        }

        $methodsStr = implode("\n\n", $methods);

        // Add CursorResult import when the interface has :cursor methods
        $hasCursor = !empty(array_filter($queries, fn($q) => $q->returns === ReturnType::Cursor));
        $cursorImport = $hasCursor ? "\nuse SqlcPhp\\Query\\CursorResult;" : '';
        $hasPaginated = !empty(array_filter(
            $queries,
            fn($q) => $q->returns === ReturnType::Paginated
        ));
        $paginatedImport = $hasPaginated
            ? "\nuse SqlcPhp\\Query\\PaginatedResult;"
            : '';

        $code = <<<PHP
<?php

declare(strict_types=1);

namespace {$this->namespace};{$paginatedImport}{$cursorImport}

use PDO;

/**
 * Interface for `{$queryClassName}`.
 * Generated by sqlc-php — do not edit manually.
 */
interface {$interfaceName}
{
{$methodsStr}
}
PHP;

        return ['className' => $interfaceName, 'code' => $code];
    }

    // =========================================================================
    // Dispatch — one entry per return-type family
    // =========================================================================

    /**
     * Route to the correct renderer based on query flags and return type.
     *
     * Order matters only for flags that override the return type (e.g. @returning).
     * Each renderer is a pure function of the query + queryGen with no side-effects.
     */
    private function renderMethodSignature(QueryDefinition $query, QueryGenerator $queryGen): string
    {
        if ($query->returning) {
            return $this->renderReturningSignature($query, $queryGen);
        }

        return match ($query->returns) {
            ReturnType::Paginated     => $this->renderPaginatedSignature($query, $queryGen),
            ReturnType::ManyPaginated => $this->renderManyPaginatedSignature($query, $queryGen),
            ReturnType::Cursor        => $this->renderCursorSignature($query, $queryGen),
            ReturnType::Many          => $this->renderManySignature($query, $queryGen),
            ReturnType::One           => $this->renderOneSignature($query, $queryGen),
            ReturnType::Opt           => $this->renderOptSignature($query, $queryGen),
            ReturnType::Exec          => $this->renderExecSignature($query, $queryGen),
            ReturnType::Batch         => $this->renderBatchSignature($query, $queryGen),
            ReturnType::Transaction   => $this->renderTransactionSignature($query, $queryGen),
            default                   => $this->renderFallbackSignature($query, $queryGen),
        };
    }

    // =========================================================================
    // Renderers — one per return-type family
    // =========================================================================

    /**
     * :cursor — keyset pagination. Returns CursorResult<ModelClass>.
     */
    private function renderCursorSignature(QueryDefinition $query, QueryGenerator $queryGen): string
    {
        $returnClass = $queryGen->resolveReturnClassPublic($query);
        $paramList   = $queryGen->buildParamListPublic($query);
        $sep         = $paramList !== '' ? ', ' : '';

        if ($query->searchable) {
            $criteriaClass = $query->group . 'Criteria';
            $paramList     = $paramList . $sep . "?{$criteriaClass} \$criteria = null, ?string \$after = null, int \$limit = 20";
        } else {
            $paramList = $paramList . $sep . '?string $after = null, int $limit = 20';
        }

        $docblock = $this->buildDocblock($query, $queryGen, "@return CursorResult<{$returnClass}>");

        return <<<PHP
{$docblock}
    public function {$query->name}({$paramList}): CursorResult;
PHP;
    }

    /**
     * @returning — INSERT that fetches and returns the created model.
     */
    private function renderReturningSignature(QueryDefinition $query, QueryGenerator $queryGen): string
    {
        $tableName   = $query->fromTable ?? '';
        $returnClass = $query->modelClass
            ?? (new \SqlcPhp\Parser\QueryParser())->toPascalCase(
                (new \SqlcPhp\Parser\QueryParser())->toSingular($tableName)
            );
        $paramList = $queryGen->buildParamListPublic($query);
        $docblock  = $this->buildDocblock($query, $queryGen, "@return {$returnClass}");

        return <<<PHP
{$docblock}
    public function {$query->name}({$paramList}): {$returnClass};
PHP;
    }

    /**
     * :paginated — returns PaginatedResult<ModelClass>.
     * Can be combined with @searchable (adds $criteria + int $limit + int $offset).
     */
    private function renderPaginatedSignature(QueryDefinition $query, QueryGenerator $queryGen): string
    {
        $returnClass = $queryGen->resolveReturnClassPublic($query);
        $paramList   = $queryGen->buildParamListPublic($query);

        if ($query->searchable) {
            $criteriaClass = $query->group . 'Criteria';
            $sep       = $paramList !== '' ? ', ' : '';
            $paramList = $paramList . $sep . "?{$criteriaClass} \$criteria = null, int \$limit = 10, int \$offset = 0";
        } else {
            $sep       = $paramList !== '' ? ', ' : '';
            $paramList = $paramList . $sep . 'int $limit = 10, int $offset = 0';
        }

        return <<<PHP
    /**
     * @return PaginatedResult<{$returnClass}>
     */
    public function {$query->name}({$paramList}): PaginatedResult;
PHP;
    }

    /**
     * :many-paginated — returns array with optional $limit/$offset.
     * Can be combined with @searchable and/or @counted.
     */
    private function renderManyPaginatedSignature(QueryDefinition $query, QueryGenerator $queryGen): string
    {
        $returnClass = $queryGen->resolveReturnClassPublic($query);
        $paramList   = $queryGen->buildParamListPublic($query);

        if ($query->searchable) {
            $criteriaClass = $query->group . 'Criteria';
            $sep       = $paramList !== '' ? ', ' : '';
            $paramList = $paramList . $sep . "?{$criteriaClass} \$criteria = null, ?int \$limit = null, int \$offset = 0";

            $main = "    /** @searchable */\n    public function {$query->name}({$paramList}): array;";

            if ($query->counted) {
                $countParams = $queryGen->buildParamListPublic($query);
                $sep2        = $countParams !== '' ? ', ' : '';
                $countParams = $countParams . $sep2 . "?{$criteriaClass} \$criteria = null";
                $countName   = $query->name . 'Count';
                $main .= "\n\n    public function {$countName}({$countParams}): int;";
            }

            return $main;
        }

        $sep       = $paramList !== '' ? ', ' : '';
        $paramList = $paramList . $sep . '?int $limit = null, int $offset = 0';
        $docblock  = $this->buildDocblock($query, $queryGen, "@return {$returnClass}[]");

        $main = <<<PHP
{$docblock}
    public function {$query->name}({$paramList}): array;
PHP;

        if ($query->counted) {
            $countParamList = $queryGen->buildParamListPublic($query);
            $countName      = $query->name . 'Count';
            $main .= <<<PHP


    /**
     * Total rows matching the filter conditions (without pagination).
     * @return int
     */
    public function {$countName}({$countParamList}): int;
PHP;
        }

        return $main;
    }

    /**
     * :many — can be combined with @searchable.
     */
    private function renderManySignature(QueryDefinition $query, QueryGenerator $queryGen): string
    {
        $returnClass = $queryGen->resolveReturnClassPublic($query);
        $paramList   = $queryGen->buildParamListPublic($query);

        if ($query->searchable) {
            $criteriaClass = $query->group . 'Criteria';
            $sep       = $paramList !== '' ? ', ' : '';
            $paramList = $paramList . $sep . "?{$criteriaClass} \$criteria = null";
            return "    /** @searchable */\n    public function {$query->name}({$paramList}): array;";
        }

        $docblock = $this->buildDocblock($query, $queryGen, "@return {$returnClass}[]");
        return <<<PHP
{$docblock}
    public function {$query->name}({$paramList}): array;
PHP;
    }

    /**
     * :one — returns model, throws if not found.
     */
    private function renderOneSignature(QueryDefinition $query, QueryGenerator $queryGen): string
    {
        $returnClass = $queryGen->resolveReturnClassPublic($query);
        $paramList   = $queryGen->buildParamListPublic($query);
        $docblock    = $this->buildDocblock($query, $queryGen, "@return {$returnClass}");

        return <<<PHP
{$docblock}
    public function {$query->name}({$paramList}): {$returnClass};
PHP;
    }

    /**
     * :opt — returns model or null.
     */
    private function renderOptSignature(QueryDefinition $query, QueryGenerator $queryGen): string
    {
        $returnClass = $queryGen->resolveReturnClassPublic($query);
        $paramList   = $queryGen->buildParamListPublic($query);
        $docblock    = $this->buildDocblock($query, $queryGen, "@return {$returnClass}|null");

        return <<<PHP
{$docblock}
    public function {$query->name}({$paramList}): ?{$returnClass};
PHP;
    }

    /**
     * :exec — void (INSERT / UPDATE / DELETE).
     */
    private function renderExecSignature(QueryDefinition $query, QueryGenerator $queryGen): string
    {
        $paramList = $queryGen->buildParamListPublic($query);
        $docblock  = $this->buildDocblock($query, $queryGen, '@return void');

        return <<<PHP
{$docblock}
    public function {$query->name}({$paramList}): void;
PHP;
    }

    /**
     * :batch — executes query N times, returns total rows affected.
     */
    private function renderBatchSignature(QueryDefinition $query, QueryGenerator $queryGen): string
    {
        $paramList = $queryGen->buildParamListPublic($query);
        $docblock  = $this->buildDocblock($query, $queryGen, '@return int  Total rows affected.');

        return <<<PHP
{$docblock}
    public function {$query->name}({$paramList}): int;
PHP;
    }

    /**
     * :transaction — orchestrates multiple :exec methods in one DB transaction.
     */
    private function renderTransactionSignature(QueryDefinition $query, QueryGenerator $queryGen): string
    {
        $paramList = $queryGen->buildParamListPublic($query);
        $docblock  = $this->buildDocblock($query, $queryGen, '@return void');

        return <<<PHP
{$docblock}
    public function {$query->name}({$paramList}): void;
PHP;
    }

    /**
     * Fallback for any return type not explicitly handled above.
     */
    private function renderFallbackSignature(QueryDefinition $query, QueryGenerator $queryGen): string
    {
        $returnType = $queryGen->resolveReturnTypePublic($query);
        $paramList  = $queryGen->buildParamListPublic($query);
        $docblock   = $this->buildDocblock($query, $queryGen, "@return {$returnType}");

        return <<<PHP
{$docblock}
    public function {$query->name}({$paramList}): {$returnType};
PHP;
    }

    // =========================================================================
    // Shared helpers
    // =========================================================================

    /**
     * Build a PHPDoc block for a method signature.
     *
     * @param string $returnTag  e.g. "@return User[]" or "@return void"
     */
    private function buildDocblock(
        QueryDefinition $query,
        QueryGenerator  $queryGen,
        string          $returnTag = '',
    ): string {
        $lines = ['    /**'];

        if ($query->deprecated !== null) {
            $lines[] = '     * @deprecated ' . $query->deprecated;
        }

        foreach ($query->params as $param) {
            $type    = $param->optional
                ? (str_starts_with($param->phpType, '?') ? $param->phpType : '?' . $param->phpType)
                : $param->phpType;
            $note    = $param->optional ? ' Pass null to skip this filter.' : '';
            $lines[] = "     * @param {$type} \${$param->name}{$note}";
        }

        if ($returnTag !== '') {
            $lines[] = "     * {$returnTag}";
        }

        $lines[] = '     */';
        return implode("\n", $lines);
    }
}
