<?php

declare(strict_types=1);

namespace SqlcPhp\Generator;

use SqlcPhp\Catalog\SchemaCatalog;
use SqlcPhp\TypeMapper\TypeMapperInterface;

/**
 * Generates typed DTO classes for columns declared with @json.
 *
 * When a query has a JSON_ARRAYAGG column annotated as:
 *   -- @json cities City
 *
 * This generator produces a `City.php` readonly DTO whose properties are
 * inferred from the schema table whose singular name matches the class name.
 *
 * The generated class is always a standalone readonly DTO with a fromRow()
 * that casts each property from the decoded JSON object (plain PHP array).
 *
 * Placement follows scoped_dtos: the caller passes the target namespace
 * and the ResultDtoGenerator handles routing to the correct directory.
 *
 * Example output for `City` resolved against a `cities` table:
 *
 *   readonly class City
 *   {
 *       public function __construct(
 *           public int    $id,
 *           public string $name,
 *           public string $slug,
 *       ) {}
 *
 *       public static function fromRow(array $row): self
 *       {
 *           return new self(
 *               id:   (int) $row['id'],
 *               name: (string) $row['name'],
 *               slug: (string) $row['slug'],
 *           );
 *       }
 *   }
 */
class JsonDtoGenerator
{
    public function __construct(
        private readonly SchemaCatalog        $catalog,
        private readonly TypeMapperInterface  $typeMapper,
    ) {}

    /**
     * Generate a typed DTO for a @json column.
     *
     * @param  string $className   The DTO class name declared in @json (e.g. "City")
     * @param  string $namespace   The PHP namespace to declare (respects scoped_dtos)
     * @param  string $tableName   The resolved table name in the schema (e.g. "cities")
     * @return array{className: string, code: string}
     *
     * @throws \RuntimeException When the table is not found in the schema catalog
     */
    public function generate(string $className, string $namespace, string $tableName): array
    {
        $table = $this->catalog->getTable($tableName);
        if ($table === null) {
            throw new \RuntimeException(
                "@json annotation references class '{$className}' but no matching table " .
                "'{$tableName}' was found in the schema. " .
                "Declare the table in your schema.sql or use a virtual_table entry."
            );
        }

        $props    = [];
        $fromArgs = [];

        foreach ($table->columns as $col) {
            $phpType = $this->typeMapper->toPhpType(
                $col->sqlType,
                $col->nullable,
                $tableName,
                $col->name,
            );
            $cast      = $this->typeMapper->fromRowCast($phpType, $col->name, $col->nullable);
            $props[]   = "        public {$phpType} \${$col->name},";
            $fromArgs[] = "            {$cast},";
        }

        $propsStr    = implode("\n", $props);
        $fromArgsStr = implode("\n", $fromArgs);

        $code = <<<PHP
<?php

declare(strict_types=1);

namespace {$namespace};

/**
 * JSON DTO for @json-annotated columns — generated by sqlc-php, do not edit manually.
 * Inferred from the `{$tableName}` table schema.
 */
readonly class {$className}
{
    public function __construct(
{$propsStr}
    ) {}

    /**
     * Hydrate from a decoded JSON object (associative array).
     *
     * @param array<string, mixed> \$row
     */
    public static function fromRow(array \$row): self
    {
        return new self(
{$fromArgsStr}
        );
    }
}
PHP;

        return ['className' => $className, 'code' => $code];
    }

    /**
     * Resolve the schema table name for a given DTO class name.
     *
     * Strategy (in order):
     *   1. Exact match — class name IS the table name (e.g. City → city table)
     *   2. Lowercase match — City → city
     *   3. Pluralized lowercase — City → cities (append 's' or 'es' heuristic)
     *   4. Caller already knows the table name — passed directly
     *
     * Returns null when no table can be matched; the caller throws a clear error.
     */
    public function resolveTableName(string $className): ?string
    {
        $lower    = strtolower($className);
        $tables   = $this->catalog->tableNames();

        // 1. Exact match (case-insensitive)
        foreach ($tables as $t) {
            if (strtolower($t) === $lower) return $t;
        }

        // 2. Simple plural: append 's'
        foreach ($tables as $t) {
            if (strtolower($t) === $lower . 's') return $t;
        }

        // 3. Plural with 'es' (city → cities, country → countries)
        $withEs = rtrim($lower, 'y') . (str_ends_with($lower, 'y') ? 'ies' : 'es');
        foreach ($tables as $t) {
            if (strtolower($t) === $withEs) return $t;
        }

        return null;
    }
}
