<?php

declare(strict_types=1);

namespace SqlcPhp\Generator;

use SqlcPhp\Catalog\SchemaCatalog;
use SqlcPhp\Generator\ExtensionData;
use SqlcPhp\Generator\ExtensionGenerator;
use SqlcPhp\Parser\QueryParser;
use SqlcPhp\TypeMapper\TypeMapperInterface;

/**
 * Generates PHP readonly DTO classes from table definitions.
 *
 * Each table yields one class, e.g. `users` → `User`.
 * The constructor uses PHP 8.4 property promotion.
 */
class ModelGenerator
{
    public function __construct(
        private readonly SchemaCatalog  $catalog,
        private readonly TypeMapperInterface $typeMapper,
        private readonly QueryParser    $queryParser,
        private readonly string         $namespace,
        private readonly string         $datetimeFormat = 'Y-m-d H:i:s',
    ) {}

    /**
     * Generate a PHP class file for the given table name.
     *
     * When $extGen is provided, the generated class will include a
     * `use XExtension;` statement and the scaffold will be returned
     * in the result array under 'extension'.
     *
     * @return array{className: string, code: string, extension?: ExtensionData}
     */
    public function generate(string $tableName, ?ExtensionGenerator $extGen = null): array
    {
        $table     = $this->catalog->getTable($tableName);
        $columns   = $table?->columns ?? [];
        $singular  = $this->queryParser->toPascalCase($this->queryParser->toSingular($tableName));
        $className = $singular;

        $props = [];
        foreach ($columns as $col) {
            $phpType = $this->typeMapper->toPhpType($col->sqlType, $col->nullable, $tableName, $col->name);
            $props[] = "        public {$phpType} \${$col->name},";
        }

        $propsStr = implode("\n", $props);

        $code = <<<PHP
<?php

declare(strict_types=1);

namespace {$this->namespace};

/**
 * DTO for the `{$tableName}` table.
 * Generated by sqlc-php — do not edit manually.
 */
readonly class {$className}
{
    public function __construct(
{$propsStr}
    ) {}

    /**
     * Hydrate from a PDO result row (associative array).
     *
     * @param array<string, mixed> \$row
     */
    public static function fromRow(array \$row): self
    {
        return new self(
{$this->buildFromRowArgs($columns, $tableName)}
        );
    }

    /**
     * Convert to an associative array.
     * BackedEnum values are unwrapped to their scalar value.
     * DateTimeImmutable values are formatted as '{$this->datetimeFormat}'.
     *
     * @return array<string, mixed>
     */
    public function toArray(): array
    {
        return [
{$this->buildModelToArrayBody($columns, $tableName)}
        ];
    }
}
PHP;

        // Inject extension trait if ExtensionGenerator is provided
        if ($extGen !== null) {
            $propDefs = array_map(fn($col) => [
                'name'    => $col->name,
                'phpType' => $this->typeMapper->toPhpType($col->sqlType, $col->nullable, $tableName, $col->name),
                'fqcn'    => $this->typeMapper->toPhpFqcn($col->sqlType, $tableName, $col->name),
            ], $columns);
            $hostFqcn = $this->namespace . '\\' . $className;
            $ext      = $extGen->forModel($className, $propDefs, $hostFqcn);
            $code     = $extGen->injectIntoClass($code, $ext);
            return ['className' => $className, 'code' => $code, 'extension' => $ext];
        }

        return ['className' => $className, 'code' => $code];
    }

    private function buildModelToArrayBody(array $columns, string $tableName): string
    {
        $lines = [];
        foreach ($columns as $col) {
            $phpType  = $this->typeMapper->toPhpType($col->sqlType, $col->nullable, $tableName, $col->name);
            $nullable = str_starts_with($phpType, '?');
            $bare     = ltrim($phpType, '?');
            $expr     = "\$this->{$col->name}";

            if ($this->typeMapper->needsValueExtraction($phpType)) {
                $val = $nullable ? "{$expr}?->value" : "{$expr}->value";
            } elseif (in_array($bare, ['\\DateTimeImmutable', 'DateTimeImmutable', '\\DateTime', 'DateTime'], true)) {
                $fmt = addslashes($this->datetimeFormat);
                $val = $nullable ? "{$expr}?->format('{$fmt}')" : "{$expr}->format('{$fmt}')";
            } else {
                $val = $expr;
            }

            $lines[] = "            '{$col->name}' => {$val},";
        }
        return implode("\n", $lines);
    }

    private function buildFromRowArgs(array $columns, string $tableName = ''): string
    {
        $lines = [];
        foreach ($columns as $col) {
            $phpType = $this->typeMapper->toPhpType($col->sqlType, $col->nullable, $tableName, $col->name);
            $cast    = $this->typeMapper->fromRowCast($phpType, $col->name, $col->nullable);
            $lines[] = "            {$cast},";
        }
        return implode("\n", $lines);
    }
}
