<?php

declare(strict_types=1);

namespace SqlcPhp\Generator;

use SqlcPhp\Catalog\SchemaCatalog;
use SqlcPhp\Parser\QueryParser;
use SqlcPhp\TypeMapper\MySQLTypeMapper;

/**
 * Generates PHP readonly DTO classes from table definitions.
 *
 * Each table yields one class, e.g. `users` → `User`.
 * The constructor uses PHP 8.4 property promotion.
 */
class ModelGenerator
{
    public function __construct(
        private readonly SchemaCatalog  $catalog,
        private readonly MySQLTypeMapper $typeMapper,
        private readonly QueryParser    $queryParser,
        private readonly string         $namespace,
    ) {}

    /**
     * Generate a PHP class file for the given table name.
     *
     * @return array{className: string, code: string}
     */
    public function generate(string $tableName): array
    {
        $table     = $this->catalog->getTable($tableName);
        $columns   = $table?->columns ?? [];
        $singular  = $this->queryParser->toPascalCase($this->queryParser->toSingular($tableName));
        $className = $singular;

        $props = [];
        foreach ($columns as $col) {
            $phpType = $this->typeMapper->toPhpType($col->sqlType, $col->nullable, $tableName, $col->name);
            $props[] = "        public {$phpType} \${$col->name},";
        }

        $propsStr = implode("\n", $props);

        $code = <<<PHP
<?php

declare(strict_types=1);

namespace {$this->namespace};

/**
 * DTO for the `{$tableName}` table.
 * Generated by sqlc-php — do not edit manually.
 */
readonly class {$className}
{
    public function __construct(
{$propsStr}
    ) {}

    /**
     * Hydrate from a PDO result row (associative array).
     *
     * @param array<string, mixed> \$row
     */
    public static function fromRow(array \$row): self
    {
        return new self(
{$this->buildFromRowArgs($columns, $tableName)}
        );
    }
}
PHP;

        return ['className' => $className, 'code' => $code];
    }

    private function buildFromRowArgs(array $columns, string $tableName = ''): string
    {
        $lines = [];
        foreach ($columns as $col) {
            $phpType = $this->typeMapper->toPhpType($col->sqlType, $col->nullable, $tableName, $col->name);
            $cast    = $this->buildCast($phpType, $col->name, $col->nullable, $col->sqlType);
            $lines[] = "            {$cast},";
        }
        return implode("\n", $lines);
    }

    private function buildCast(string $phpType, string $colName, bool $nullable, string $sqlType = ''): string
    {
        $base   = ltrim($phpType, '?\\');
        $access = "\$row['{$colName}']";
        $upper  = strtoupper(trim(preg_replace('/\(.*\)/s', '', $sqlType) ?? $sqlType));

        // ENUM backed enum → EnumClass::from() / ::tryFrom()
        if ($upper === 'ENUM') {
            if ($nullable) {
                return "isset({$access}) ? {$base}::tryFrom((string) {$access}) : null";
            }
            return "{$base}::from((string) {$access})";
        }

        // JSON → array via json_decode
        if ($upper === 'JSON' || $base === 'array') {
            if ($nullable) {
                return "isset({$access}) ? json_decode((string) {$access}, true) : null";
            }
            return "json_decode((string) {$access}, true) ?? []";
        }

        if ($nullable) {
            return match($base) {
                'int'   => "isset({$access}) ? (int) {$access} : null",
                'float' => "isset({$access}) ? (float) {$access} : null",
                'bool'  => "isset({$access}) ? (bool) {$access} : null",
                default => "{$access} ?? null",
            };
        }

        return match($base) {
            'int'   => "(int) {$access}",
            'float' => "(float) {$access}",
            'bool'  => "(bool) {$access}",
            'mixed' => "{$access}",
            default => "(string) {$access}",
        };
    }
}
