<?php

declare(strict_types=1);

namespace SqlcPhp\Generator;

use SqlcPhp\Catalog\SchemaCatalog;
use SqlcPhp\Parser\QueryDefinition;
use SqlcPhp\Parser\ReturnType;
use SqlcPhp\Resolver\QueryParam;
use SqlcPhp\TypeMapper\MySQLTypeMapper;

/**
 * Generates one PHP Query class per @group, containing one method per query.
 */
class QueryGenerator
{
    public function __construct(
        private readonly SchemaCatalog      $catalog,
        private readonly MySQLTypeMapper    $typeMapper,
        private readonly ResultDtoGenerator $resultDtoGen,
        private readonly string             $namespace,
        private readonly bool               $generateInterfaces = false,
        private readonly ?InterfaceGenerator $interfaceGen = null,
    ) {}

    /**
     * @param  QueryDefinition[] $queries
     * @return array<string, array{className: string, code: string}>
     */
    public function generate(array $queries): array
    {
        $groups = [];
        foreach ($queries as $query) {
            $groups[$query->group][] = $query;
        }

        $files = [];
        foreach ($groups as $group => $groupQueries) {
            $className = $group . 'Query';
            $code = $this->renderClass($className, $groupQueries);
            $files[$className] = ['className' => $className, 'code' => $code];
        }

        return $files;
    }

    /**
     * Generate interface files for all query groups.
     * Returns empty array when interface generation is disabled.
     *
     * @param  QueryDefinition[] $queries
     * @return array<string, array{className: string, code: string}>
     */
    public function generateInterfaces(array $queries): array
    {
        if (!$this->generateInterfaces || $this->interfaceGen === null) {
            return [];
        }

        $groups = [];
        foreach ($queries as $query) {
            $groups[$query->group][] = $query;
        }

        $files = [];
        foreach ($groups as $group => $groupQueries) {
            $queryClassName = $group . 'Query';
            ['className' => $cls, 'code' => $code] =
                $this->interfaceGen->generate($queryClassName, $groupQueries, $this);
            $files[$cls] = ['className' => $cls, 'code' => $code];
        }

        return $files;
    }

    /** @param QueryDefinition[] $queries */
    private function renderClass(string $className, array $queries): string
    {
        $methods      = array_map(fn($q) => $this->renderMethod($q), $queries);
        $methodsStr   = implode("\n\n", $methods);
        $implements   = ($this->generateInterfaces && $this->interfaceGen !== null)
            ? ' implements ' . $this->interfaceGen->interfaceName($className)
            : '';

        return <<<PHP
<?php

declare(strict_types=1);

namespace {$this->namespace};

use PDO;
use RuntimeException;

/**
 * Query class for the `{$className}` group.
 * Generated by sqlc-php — do not edit manually.
 */
class {$className}{$implements}
{
    public function __construct(
        private readonly PDO \$pdo,
    ) {}

{$methodsStr}
}
PHP;
    }

    private function renderMethod(QueryDefinition $query): string
    {
        return match ($query->returns->value) {
            ':many'           => $this->renderManyMethod($query),
            ':many-paginated' => $this->renderManyPaginatedMethod($query),
            ':one'            => $this->renderOneMethod($query),
            ':opt'            => $this->renderOptMethod($query),
            ':exec'           => $this->renderExecMethod($query),
            default           => $this->renderManyMethod($query),
        };
    }

    // -------------------------------------------------------------------------
    // :many
    // -------------------------------------------------------------------------

    private function renderManyMethod(QueryDefinition $query): string
    {
        $returnClass = $this->resolveReturnClass($query);
        $signature   = $this->buildSignature($query, "array");
        $docblock    = $this->buildDocblock($query, "@return {$returnClass}[]");
        $sqlLiteral  = $this->renderSqlLiteral($query->sql);
        $bindings    = $this->renderBindings($query);

        return <<<PHP
{$docblock}
    public function {$signature}
    {
        \$stmt = \$this->pdo->prepare({$sqlLiteral});
{$bindings}        \$stmt->execute();

        return array_map(
            static fn(array \$row): {$returnClass} => {$returnClass}::fromRow(\$row),
            \$stmt->fetchAll(PDO::FETCH_ASSOC),
        );
    }
PHP;
    }

    // -------------------------------------------------------------------------
    // :many-paginated
    // -------------------------------------------------------------------------

    private function renderManyPaginatedMethod(QueryDefinition $query): string
    {
        $returnClass = $this->resolveReturnClass($query);

        // Build param list: user-defined params first, then limit/offset at the end
        $userParams  = $this->buildParamList($query);
        $paginParams = $userParams !== ''
            ? ", int \$limit = 20, int \$offset = 0"
            : "int \$limit = 20, int \$offset = 0";

        $signature  = "{$query->name}({$userParams}{$paginParams}): array";

        $docReturn  = "@return {$returnClass}[]";
        $docblock   = $this->buildDocblockWithExtra($query, $docReturn, [
            "@param int \$limit  Maximum number of rows to return.",
            "@param int \$offset Number of rows to skip.",
        ]);

        $sqlLiteral = $this->renderSqlLiteral($query->sql);
        $bindings   = $this->renderBindings($query);

        return <<<PHP
{$docblock}
    public function {$signature}
    {
        \$stmt = \$this->pdo->prepare({$sqlLiteral});
{$bindings}        \$stmt->bindValue(':limit',  \$limit,  PDO::PARAM_INT);
        \$stmt->bindValue(':offset', \$offset, PDO::PARAM_INT);
        \$stmt->execute();

        return array_map(
            static fn(array \$row): {$returnClass} => {$returnClass}::fromRow(\$row),
            \$stmt->fetchAll(PDO::FETCH_ASSOC),
        );
    }
PHP;
    }

    // -------------------------------------------------------------------------
    // :one — throws if no row found
    // -------------------------------------------------------------------------

    private function renderOneMethod(QueryDefinition $query): string
    {
        $returnClass = $this->resolveReturnClass($query);
        $signature   = $this->buildSignature($query, $returnClass);
        $docblock    = $this->buildDocblock($query, "@return {$returnClass}");
        $sqlLiteral  = $this->renderSqlLiteral($query->sql);
        $bindings    = $this->renderBindings($query);
        $exception   = 'No record found for query "' . $query->name . '"';

        return <<<PHP
{$docblock}
    public function {$signature}
    {
        \$stmt = \$this->pdo->prepare({$sqlLiteral});
{$bindings}        \$stmt->execute();

        \$row = \$stmt->fetch(PDO::FETCH_ASSOC);
        if (\$row === false) {
            throw new RuntimeException('{$exception}');
        }

        return {$returnClass}::fromRow(\$row);
    }
PHP;
    }

    // -------------------------------------------------------------------------
    // :opt — returns null if no row found
    // -------------------------------------------------------------------------

    private function renderOptMethod(QueryDefinition $query): string
    {
        $returnClass = $this->resolveReturnClass($query);
        $signature   = $this->buildSignature($query, "?{$returnClass}");
        $docblock    = $this->buildDocblock($query, "@return {$returnClass}|null");
        $sqlLiteral  = $this->renderSqlLiteral($query->sql);
        $bindings    = $this->renderBindings($query);

        return <<<PHP
{$docblock}
    public function {$signature}
    {
        \$stmt = \$this->pdo->prepare({$sqlLiteral});
{$bindings}        \$stmt->execute();

        \$row = \$stmt->fetch(PDO::FETCH_ASSOC);
        return \$row !== false ? {$returnClass}::fromRow(\$row) : null;
    }
PHP;
    }

    // -------------------------------------------------------------------------
    // :exec
    // -------------------------------------------------------------------------

    private function renderExecMethod(QueryDefinition $query): string
    {
        $signature  = $this->buildSignature($query, 'void');
        $docblock   = $this->buildDocblock($query, 'Executes the statement.');
        $sqlLiteral = $this->renderSqlLiteral($query->sql);
        $bindings   = $this->renderBindings($query);

        return <<<PHP
{$docblock}
    public function {$signature}
    {
        \$stmt = \$this->pdo->prepare({$sqlLiteral});
{$bindings}        \$stmt->execute();
    }
PHP;
    }

    // -------------------------------------------------------------------------
    // Public API for InterfaceGenerator
    // -------------------------------------------------------------------------

    /**
     * Returns the PHP return type string for a given query.
     * Exposed publicly so InterfaceGenerator can produce matching signatures.
     */
    public function resolveReturnTypePublic(QueryDefinition $query): string
    {
        return match ($query->returns->value) {
            ':many', ':many-paginated' => 'array',
            ':one'                     => $this->resolveReturnClass($query),
            ':opt'                     => '?' . $this->resolveReturnClass($query),
            ':exec'                    => 'void',
            default                    => 'array',
        };
    }

    /**
     * Returns the PHP parameter list string for a given query.
     * Exposed publicly so InterfaceGenerator can produce matching signatures.
     */
    public function buildParamListPublic(QueryDefinition $query): string
    {
        return $this->buildParamList($query);
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private function resolveReturnClass(QueryDefinition $query): string
    {
        if ($query->returnsModelDirectly && $query->modelClass !== null) {
            return $query->modelClass;
        }

        if (!empty($query->resultColumns)) {
            return $this->resultDtoGen->dtoClassName($query);
        }

        return 'array';
    }

    /**
     * Build the method signature: `methodName(type $param, ...): returnType`
     */
    private function buildSignature(QueryDefinition $query, string $returnType): string
    {
        $params = $this->buildParamList($query);
        return "{$query->name}({$params}): {$returnType}";
    }

    /**
     * Build a PHP parameter list from resolved QueryParams.
     * Optional params receive a `= null` default value.
     */
    private function buildParamList(QueryDefinition $query): string
    {
        if (empty($query->params)) return '';

        $required = [];
        $optional = [];

        foreach ($query->params as $param) {
            if ($param->optional) {
                // Ensure the type is nullable — optional always accepts null
                $type     = str_starts_with($param->phpType, '?')
                    ? $param->phpType
                    : '?' . $param->phpType;
                $optional[] = "{$type} \${$param->name} = null";
            } else {
                $required[] = "{$param->phpType} \${$param->name}";
            }
        }

        // Required params first, optional params last
        return implode(', ', array_merge($required, $optional));
    }

    /**
     * Build the docblock comment.
     */
    private function buildDocblock(QueryDefinition $query, string $returnTag): string
    {
        $lines = ['    /**'];

        // @deprecated tag — before @param lines, per PHPDoc convention
        if ($query->deprecated !== null) {
            $msg     = $query->deprecated !== '' ? ' ' . $query->deprecated : '';
            $lines[] = "     * @deprecated{$msg}";
        }

        foreach ($query->params as $param) {
            $type  = $param->optional
                ? (str_starts_with($param->phpType, '?') ? $param->phpType : '?' . $param->phpType)
                : $param->phpType;
            $note  = $param->optional ? ' Pass null to skip this filter.' : '';
            $lines[] = "     * @param {$type} \${$param->name}{$note}";
        }

        $lines[] = "     * {$returnTag}";
        $lines[] = '     */';

        return implode("\n", $lines);
    }

    /**
     * Build the docblock comment with extra @param lines appended before @return.
     * Used for :many-paginated to document limit/offset params.
     *
     * @param string[] $extraParamLines
     */
    private function buildDocblockWithExtra(QueryDefinition $query, string $returnTag, array $extraParamLines): string
    {
        $lines = ['    /**'];

        if ($query->deprecated !== null) {
            $msg     = $query->deprecated !== '' ? ' ' . $query->deprecated : '';
            $lines[] = "     * @deprecated{$msg}";
        }

        foreach ($query->params as $param) {
            $type    = $param->optional
                ? (str_starts_with($param->phpType, '?') ? $param->phpType : '?' . $param->phpType)
                : $param->phpType;
            $note    = $param->optional ? ' Pass null to skip this filter.' : '';
            $lines[] = "     * @param {$type} \${$param->name}{$note}";
        }

        foreach ($extraParamLines as $line) {
            $lines[] = "     * {$line}";
        }

        $lines[] = "     * {$returnTag}";
        $lines[] = '     */';

        return implode("\n", $lines);
    }
    private function renderBindings(QueryDefinition $query): string
    {
        if (empty($query->params)) return '';

        $lines = [];
        foreach ($query->params as $param) {
            $lines[] = "        \$stmt->bindValue(':{$param->name}', \${$param->name}, {$param->pdoParam});";
        }

        return implode("\n", $lines) . "\n";
    }

    /**
     * Normalise SQL into a single-line PHP single-quoted string literal.
     */
    private function renderSqlLiteral(string $sql): string
    {
        $oneLine = preg_replace('/\s+/', ' ', trim($sql)) ?? $sql;
        $escaped = str_replace("'", "\\'", $oneLine);
        return "'{$escaped}'";
    }
}
