<?php

declare(strict_types=1);

namespace SqlcPhp\Generator;

use SqlcPhp\Catalog\SchemaCatalog;
use SqlcPhp\Parser\QueryDefinition;
use SqlcPhp\Parser\ReturnType;
use SqlcPhp\Resolver\QueryParam;
use SqlcPhp\TypeMapper\TypeMapperInterface;

/**
 * Generates one PHP Query class per @group, containing one method per query.
 */
class QueryGenerator
{
    public function __construct(
        private readonly SchemaCatalog      $catalog,
        private readonly TypeMapperInterface    $typeMapper,
        private readonly ResultDtoGenerator $resultDtoGen,
        private readonly string             $namespace,
        private readonly bool               $generateInterfaces     = false,
        private readonly ?InterfaceGenerator $interfaceGen          = null,
        private readonly bool               $preparedStatementCache = false,
    ) {}

    /**
     * @param  QueryDefinition[] $queries
     * @return array<string, array{className: string, code: string}>
     */
    public function generate(array $queries): array
    {
        $groups = [];
        foreach ($queries as $query) {
            $groups[$query->group][] = $query;
        }

        $files = [];
        foreach ($groups as $group => $groupQueries) {
            $className = $group . 'Query';
            $code = $this->renderClass($className, $groupQueries);
            $files[$className] = ['className' => $className, 'code' => $code];
        }

        return $files;
    }

    /**
     * Generate interface files for all query groups.
     * Returns empty array when interface generation is disabled.
     *
     * @param  QueryDefinition[] $queries
     * @return array<string, array{className: string, code: string}>
     */
    public function generateInterfaces(array $queries): array
    {
        if (!$this->generateInterfaces || $this->interfaceGen === null) {
            return [];
        }

        $groups = [];
        foreach ($queries as $query) {
            $groups[$query->group][] = $query;
        }

        $files = [];
        foreach ($groups as $group => $groupQueries) {
            $queryClassName = $group . 'Query';
            ['className' => $cls, 'code' => $code] =
                $this->interfaceGen->generate($queryClassName, $groupQueries, $this);
            $files[$cls] = ['className' => $cls, 'code' => $code];
        }

        return $files;
    }

    /** @param QueryDefinition[] $queries */
    private function renderClass(string $className, array $queries): string
    {
        $methods      = array_map(fn($q) => $this->renderMethod($q), $queries);
        $methodsStr   = implode("\n\n", $methods);
        $implements   = ($this->generateInterfaces && $this->interfaceGen !== null)
            ? ' implements ' . $this->interfaceGen->interfaceName($className)
            : '';

        // Prepared statement cache property — only included when the feature is on
        $stmtsProperty = $this->preparedStatementCache
            ? "\n    /** @var array<string, \\PDOStatement> */\n    private array \$stmts = [];\n"
            : '';

        return <<<PHP
<?php

declare(strict_types=1);

namespace {$this->namespace};

use PDO;
use RuntimeException;

/**
 * Query class for the `{$className}` group.
 * Generated by sqlc-php — do not edit manually.
 */
class {$className}{$implements}
{
    public function __construct(
        private readonly PDO \$pdo,
    ) {}{$stmtsProperty}

{$methodsStr}
}
PHP;
    }

    private function renderMethod(QueryDefinition $query): string
    {
        $main = match ($query->returns->value) {
            ':many'           => $this->renderManyMethod($query),
            ':many-paginated' => $this->renderManyPaginatedMethod($query),
            ':one'            => $this->renderOneMethod($query),
            ':opt'            => $this->renderOptMethod($query),
            ':exec'           => $this->renderExecMethod($query),
            ':batch'          => $this->renderBatchMethod($query),
            ':transaction'    => $this->renderTransactionMethod($query),
            default           => $this->renderManyMethod($query),
        };

        // @counted on :many-paginated — emit an additional {name}Count() method
        if ($query->counted && $query->returns === ReturnType::ManyPaginated) {
            $main .= "\n\n" . $this->renderCountMethod($query);
        }

        return $main;
    }

    /**
     * Generate the $stmt = ... prepare line.
     * With prepared_statement_cache on: uses $this->stmts[__FUNCTION__] ??= ...
     * Without: direct $this->pdo->prepare(...)
     */
    private function renderPrepare(QueryDefinition $query): string
    {
        $sqlLiteral = $this->renderSqlLiteral($query->sql);
        if ($this->preparedStatementCache) {
            return "        \$stmt = \$this->stmts[__FUNCTION__] ??= \$this->pdo->prepare({$sqlLiteral});\n";
        }
        return "        \$stmt = \$this->pdo->prepare({$sqlLiteral});\n";
    }

    // -------------------------------------------------------------------------
    // :many
    // -------------------------------------------------------------------------

    private function renderManyMethod(QueryDefinition $query): string
    {
        $returnClass = $this->resolveReturnClass($query);
        $signature   = $this->buildSignature($query, "array");
        $docblock    = $this->buildDocblock($query, "@return {$returnClass}[]");
        $bindings    = $this->renderBindings($query);
        $prepare     = $this->hasInListParams($query)
            ? ''
            : $this->renderPrepare($query);
        $executeCall = $this->hasInListParams($query) ? '' : "        \$stmt->execute();\n";

        return <<<PHP
{$docblock}
    public function {$signature}
    {
{$prepare}{$bindings}{$executeCall}
        return array_map(
            static fn(array \$row): {$returnClass} => {$returnClass}::fromRow(\$row),
            \$stmt->fetchAll(PDO::FETCH_ASSOC),
        );
    }
PHP;
    }

    // -------------------------------------------------------------------------
    // :many-paginated
    // -------------------------------------------------------------------------

    private function renderManyPaginatedMethod(QueryDefinition $query): string
    {
        $returnClass = $this->resolveReturnClass($query);

        // Build param list: user-defined params first, then limit/offset at the end
        $userParams  = $this->buildParamList($query);
        $paginParams = $userParams !== ''
            ? ", int \$limit = 20, int \$offset = 0"
            : "int \$limit = 20, int \$offset = 0";

        $signature  = "{$query->name}({$userParams}{$paginParams}): array";

        $docReturn  = "@return {$returnClass}[]";
        $docblock   = $this->buildDocblockWithExtra($query, $docReturn, [
            "@param int \$limit  Maximum number of rows to return.",
            "@param int \$offset Number of rows to skip.",
        ]);

        $sqlLiteral = $this->renderSqlLiteral($query->sql);
        $bindings   = $this->renderBindings($query);

        return <<<PHP
{$docblock}
    public function {$signature}
    {
        \$stmt = \$this->pdo->prepare({$sqlLiteral});
{$bindings}        \$stmt->bindValue(':limit',  \$limit,  PDO::PARAM_INT);
        \$stmt->bindValue(':offset', \$offset, PDO::PARAM_INT);
        \$stmt->execute();

        return array_map(
            static fn(array \$row): {$returnClass} => {$returnClass}::fromRow(\$row),
            \$stmt->fetchAll(PDO::FETCH_ASSOC),
        );
    }
PHP;
    }

    // -------------------------------------------------------------------------
    // @counted — companion COUNT method for :many-paginated
    // -------------------------------------------------------------------------

    /**
     * Generates a {name}Count() method that returns the total number of rows
     * matching the query's WHERE conditions — without LIMIT/OFFSET applied.
     *
     * SQL: SELECT COUNT(*) AS _total FROM (<original_sql>) AS _count_subquery
     *
     * The method signature mirrors the main :many-paginated method but without
     * the $limit and $offset parameters, since those don't affect the total count.
     */
    private function renderCountMethod(QueryDefinition $query): string
    {
        // Signature: same user params as the main method, no $limit/$offset
        $userParams = $this->buildParamList($query);
        $countName  = $query->name . 'Count';
        $signature  = "{$countName}({$userParams}): int";

        $docblock = $this->buildDocblock($query, '@return int Total number of rows matching the filter conditions.');

        // The SQL for the count wraps the original (already @optional-rewritten) SQL.
        // For :many-paginated, the analyzer appends LIMIT :limit OFFSET :offset to the SQL.
        // We MUST strip those before wrapping — they are not bound in the count method
        // and would cause PDO HY093 (invalid parameter number).
        $innerSql = preg_replace('/\s+/', ' ', trim($query->sql)) ?? $query->sql;
        $innerSql = rtrim($innerSql, ';');
        $innerSql = preg_replace('/\s+LIMIT\s+:limit\s+OFFSET\s+:offset\s*$/i', '', $innerSql);
        $innerSql = rtrim($innerSql);
        $countSql   = "SELECT COUNT(*) AS _total FROM ({$innerSql}) AS _count_subquery";
        $sqlLiteral = $this->renderSqlLiteral($countSql);

        // Bindings: same as the main method but without :limit/:offset
        // renderBindings only emits the user-defined params — limit/offset are
        // bound separately in renderManyPaginatedMethod, so we get exactly what we need.
        $bindings = $this->renderBindings($query);

        $prepare = $this->preparedStatementCache
            ? "        \$stmt = \$this->stmts[__FUNCTION__] ??= \$this->pdo->prepare({$sqlLiteral});\n"
            : "        \$stmt = \$this->pdo->prepare({$sqlLiteral});\n";

        return <<<PHP
{$docblock}
    public function {$signature}
    {
{$prepare}{$bindings}        \$stmt->execute();
        \$row = \$stmt->fetch(PDO::FETCH_ASSOC);

        return (int) ((\$row !== false ? \$row['_total'] : null) ?? 0);
    }
PHP;
    }

    // -------------------------------------------------------------------------
    // :one — throws if no row found
    // -------------------------------------------------------------------------

    private function renderOneMethod(QueryDefinition $query): string
    {
        $returnClass = $this->resolveReturnClass($query);
        $signature   = $this->buildSignature($query, $returnClass);
        $docblock    = $this->buildDocblock($query, "@return {$returnClass}");
        $bindings    = $this->renderBindings($query);
        $prepare     = $this->hasInListParams($query) ? '' : $this->renderPrepare($query);
        $executeCall = $this->hasInListParams($query) ? '' : "        \$stmt->execute();\n";
        $exception   = 'No record found for query "' . $query->name . '"';

        return <<<PHP
{$docblock}
    public function {$signature}
    {
{$prepare}{$bindings}{$executeCall}
        \$row = \$stmt->fetch(PDO::FETCH_ASSOC);
        if (\$row === false) {
            throw new RuntimeException('{$exception}');
        }

        return {$returnClass}::fromRow(\$row);
    }
PHP;
    }

    // -------------------------------------------------------------------------
    // :opt — returns null if no row found
    // -------------------------------------------------------------------------

    private function renderOptMethod(QueryDefinition $query): string
    {
        $returnClass = $this->resolveReturnClass($query);
        $signature   = $this->buildSignature($query, "?{$returnClass}");
        $docblock    = $this->buildDocblock($query, "@return {$returnClass}|null");
        $bindings    = $this->renderBindings($query);
        $prepare     = $this->hasInListParams($query) ? '' : $this->renderPrepare($query);
        $executeCall = $this->hasInListParams($query) ? '' : "        \$stmt->execute();\n";

        return <<<PHP
{$docblock}
    public function {$signature}
    {
{$prepare}{$bindings}{$executeCall}
        \$row = \$stmt->fetch(PDO::FETCH_ASSOC);
        return \$row !== false ? {$returnClass}::fromRow(\$row) : null;
    }
PHP;
    }

    // -------------------------------------------------------------------------
    // :exec
    // -------------------------------------------------------------------------

    private function renderExecMethod(QueryDefinition $query): string
    {
        $signature   = $this->buildSignature($query, 'void');
        $docblock    = $this->buildDocblock($query, 'Executes the statement.');
        $bindings    = $this->renderBindings($query);
        $prepare     = $this->hasInListParams($query) ? '' : $this->renderPrepare($query);
        $executeCall = $this->hasInListParams($query) ? '' : "        \$stmt->execute();\n";

        return <<<PHP
{$docblock}
    public function {$signature}
    {
{$prepare}{$bindings}{$executeCall}    }
PHP;
    }

    // -------------------------------------------------------------------------
    // Public API for InterfaceGenerator
    // -------------------------------------------------------------------------

    /**
     * Returns the PHP return type string for a given query.
     * Exposed publicly so InterfaceGenerator can produce matching signatures.
     */
    public function resolveReturnTypePublic(QueryDefinition $query): string
    {
        return match ($query->returns->value) {
            ':many', ':many-paginated' => 'array',
            ':one'                     => $this->resolveReturnClass($query),
            ':opt'                     => '?' . $this->resolveReturnClass($query),
            ':exec'                    => 'void',
            default                    => 'array',
        };
    }

    /**
     * Returns the PHP parameter list string for a given query.
     * Exposed publicly so InterfaceGenerator can produce matching signatures.
     */
    public function buildParamListPublic(QueryDefinition $query): string
    {
        return $this->buildParamList($query);
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private function resolveReturnClass(QueryDefinition $query): string
    {
        if ($query->returnsModelDirectly && $query->modelClass !== null) {
            return $query->modelClass;
        }

        if (!empty($query->resultColumns)) {
            return $this->resultDtoGen->dtoClassName($query);
        }

        return 'array';
    }

    /**
     * Build the method signature: `methodName(type $param, ...): returnType`
     */
    private function buildSignature(QueryDefinition $query, string $returnType): string
    {
        $params = $this->buildParamList($query);
        return "{$query->name}({$params}): {$returnType}";
    }

    /**
     * Build a PHP parameter list from resolved QueryParams.
     * Optional params receive a `= null` default value.
     * For :many-paginated queries, :limit and :offset are auto-injected by the
     * generator and must not appear in the user-facing parameter list.
     */
    private function buildParamList(QueryDefinition $query): string
    {
        if (empty($query->params)) return '';

        $required = [];
        $optional = [];

        // :limit and :offset are auto-injected for :many-paginated — skip them here
        $isPaginated    = $query->returns->value === ':many-paginated';
        $paginationKeys = ['limit', 'offset'];

        foreach ($query->params as $param) {
            if ($isPaginated && in_array($param->name, $paginationKeys, true)) {
                continue;
            }
            if ($param->inList) {
                $required[] = "array \${$param->name}";
            } elseif ($param->optional) {
                $type       = str_starts_with($param->phpType, '?')
                    ? $param->phpType
                    : '?' . $param->phpType;
                $optional[] = "{$type} \${$param->name} = null";
            } else {
                $required[] = "{$param->phpType} \${$param->name}";
            }
        }

        return implode(', ', array_merge($required, $optional));
    }

    /**
     * Build the docblock comment.
     */
    private function buildDocblock(QueryDefinition $query, string $returnTag): string
    {
        $lines = ['    /**'];

        if ($query->deprecated !== null) {
            $msg     = $query->deprecated !== '' ? ' ' . $query->deprecated : '';
            $lines[] = "     * @deprecated{$msg}";
        }

        foreach ($query->params as $param) {
            // Skip auto-injected pagination params for :many-paginated
            if ($query->returns->value === ':many-paginated'
                && in_array($param->name, ['limit', 'offset'], true)) {
                continue;
            }
            if ($param->inList) {
                $base     = ltrim($param->phpType, '?');
                $lines[]  = "     * @param {$base}[] \${$param->name} List of values for IN() clause — must be non-empty.";
            } elseif ($param->optional) {
                $type    = str_starts_with($param->phpType, '?')
                    ? $param->phpType
                    : '?' . $param->phpType;
                $lines[] = "     * @param {$type} \${$param->name} Pass null to skip this filter.";
            } else {
                $lines[] = "     * @param {$param->phpType} \${$param->name}";
            }
        }

        $lines[] = "     * {$returnTag}";
        $lines[] = '     */';

        return implode("\n", $lines);
    }

    /**
     * Build the docblock comment with extra @param lines appended before @return.
     * Used for :many-paginated to document limit/offset params.
     *
     * @param string[] $extraParamLines
     */
    private function buildDocblockWithExtra(QueryDefinition $query, string $returnTag, array $extraParamLines): string
    {
        $lines = ['    /**'];

        if ($query->deprecated !== null) {
            $msg     = $query->deprecated !== '' ? ' ' . $query->deprecated : '';
            $lines[] = "     * @deprecated{$msg}";
        }

        foreach ($query->params as $param) {
            if ($param->inList) {
                $base    = ltrim($param->phpType, '?');
                $lines[] = "     * @param {$base}[] \${$param->name} List of values for IN() clause — must be non-empty.";
            } elseif ($param->optional) {
                $type    = str_starts_with($param->phpType, '?')
                    ? $param->phpType
                    : '?' . $param->phpType;
                $lines[] = "     * @param {$type} \${$param->name} Pass null to skip this filter.";
            } else {
                $lines[] = "     * @param {$param->phpType} \${$param->name}";
            }
        }

        foreach ($extraParamLines as $line) {
            $lines[] = "     * {$line}";
        }

        $lines[] = "     * {$returnTag}";
        $lines[] = '     */';

        return implode("\n", $lines);
    }

    /**
     * Render the SQL setup and bindings for the method body.
     *
     * For regular queries returns simple bindValue() calls.
     * For queries with IN() params, emits runtime placeholder expansion first.
     */
    private function renderBindings(QueryDefinition $query): string
    {
        $inListParams  = array_filter($query->params, fn($p) => $p->inList);
        $regularParams = array_filter($query->params, fn($p) => !$p->inList);

        if (empty($inListParams)) {
            // Standard path: bindValue only
            if (empty($regularParams)) return '';
            $lines = [];

            // For :many-paginated, :limit and :offset are bound separately in the
            // main render method — skip them here so they don't double-bind and
            // so the count method doesn't bind them at all.
            $isPaginated    = $query->returns->value === ':many-paginated';
            $paginationKeys = ['limit', 'offset'];

            foreach ($regularParams as $param) {
                if ($isPaginated && in_array($param->name, $paginationKeys, true)) {
                    continue;
                }
                $lines[] = "        \$stmt->bindValue(':{$param->name}', \${$param->name}, {$param->pdoParam});";
                if ($param->optional) {
                    $chk = $param->name . '_chk';
                    $lines[] = "        \$stmt->bindValue(':{$chk}', \${$param->name}, {$param->pdoParam});";
                }
            }
            return empty($lines) ? '' : implode("\n", $lines) . "\n";
        }

        // Has IN params — expand placeholders at runtime
        $lines = [];
        $lines[] = '        // Expand IN() placeholders dynamically at runtime';
        $lines[] = '        $__sql = ' . $this->renderSqlLiteral($query->sql) . ';';

        foreach ($inListParams as $param) {
            $n    = "\${$param->name}";
            $ph   = "\$__ph_{$param->name}";
            $msg  = "Parameter \\\${$param->name} for IN() clause must not be empty.";
            $lines[] = "        if (empty({$n})) {";
            $lines[] = "            throw new \\InvalidArgumentException('{$msg}');";
            $lines[] = "        }";
            $lines[] = "        {$ph} = implode(',', array_fill(0, count({$n}), '?'));";
            $lines[] = "        \$__sql = str_replace(':{$param->name}', {$ph}, \$__sql);";
        }

        $lines[] = '        $stmt = $this->pdo->prepare($__sql);';

        // Bind regular named params (excluding auto-injected limit/offset for paginated)
        $isPaginated    = $query->returns->value === ':many-paginated';
        $paginationKeys = ['limit', 'offset'];

        foreach ($regularParams as $param) {
            if ($isPaginated && in_array($param->name, $paginationKeys, true)) {
                continue;
            }
            $lines[] = "        \$stmt->bindValue(':{$param->name}', \${$param->name}, {$param->pdoParam});";
            if ($param->optional) {
                $chk = $param->name . '_chk';
                $lines[] = "        \$stmt->bindValue(':{$chk}', \${$param->name}, {$param->pdoParam});";
            }
        }

        // execute() receives positional values for all IN lists merged in order
        $executeArgParts = [];
        foreach ($inListParams as $param) {
            $executeArgParts[] = "...\${$param->name}";
        }
        $executeArgs = implode(', ', $executeArgParts);
        $lines[] = "        \$stmt->execute([{$executeArgs}]);";
        $lines[] = '';

        return implode("\n", $lines) . "\n";
    }

    /**
     * Whether the query has IN-list params — affects how prepare/execute is emitted.
     */
    private function hasInListParams(QueryDefinition $query): bool
    {
        foreach ($query->params as $p) {
            if ($p->inList) return true;
        }
        return false;
    }

    // -------------------------------------------------------------------------
    // :batch — run the same query N times inside a transaction
    // -------------------------------------------------------------------------

    private function renderBatchMethod(QueryDefinition $query): string
    {
        if (empty($query->params)) {
            throw new \RuntimeException(
                "Query '{$query->name}': :batch requires at least one named parameter."
            );
        }

        // Build the shape array for the @param docblock: array{name: type, ...}
        $shapeEntries = implode(', ', array_map(
            fn($p) => $p->name . ': ' . $p->phpType,
            $query->params
        ));
        $returnTag  = "@return int Number of rows processed";
        $docblock   = $this->buildDocblock($query, $returnTag);
        $sqlLiteral = $this->renderSqlLiteral($query->sql);

        // Generate bindValue lines for a single row from $row
        $bindLines = [];
        foreach ($query->params as $param) {
            $bindLines[] = "            \$stmt->bindValue(':{$param->name}', \$row['{$param->name}'], {$param->pdoParam});";
        }
        $bindStr = implode("\n", $bindLines);

        $methodName = $query->name;
        $signature  = "function {$methodName}(array \$rows): int";

        return <<<PHP
{$docblock}
    /**
     * Executes the query once per row in \$rows, inside a single transaction.
     * Rolls back and re-throws on any failure.
     *
     * @param array<array{{$shapeEntries}}> \$rows
     */
    public {$signature}
    {
        if (empty(\$rows)) return 0;

        \$stmt = \$this->pdo->prepare({$sqlLiteral});
        \$this->pdo->beginTransaction();
        try {
            foreach (\$rows as \$row) {
{$bindStr}
                \$stmt->execute();
            }
            \$this->pdo->commit();
        } catch (\Throwable \$e) {
            \$this->pdo->rollBack();
            throw \$e;
        }

        return count(\$rows);
    }
PHP;
    }

    // -------------------------------------------------------------------------
    // :transaction — run multiple :exec queries in one transaction
    // -------------------------------------------------------------------------

    private function renderTransactionMethod(QueryDefinition $query): string
    {
        // :transaction is a meta-query — the SQL is a comma-separated list of
        // @name values to call in sequence. Format:
        //   -- @name TransferFunds
        //   -- @returns :transaction
        //   -- @calls debitAccount,creditAccount
        // The SQL body is empty; @calls references other queries in the same group.

        $signature = $this->buildSignature($query, 'void');
        $docblock  = $this->buildDocblock($query, 'Executes multiple queries in a single transaction.');

        // Parse @calls from the sql body (stored as the raw SQL for :transaction)
        $calls     = array_filter(array_map('trim', explode(',', trim($query->sql))));

        if (empty($calls)) {
            throw new \RuntimeException(
                "Query '{$query->name}': :transaction requires @calls with a comma-separated " .
                "list of method names to execute (e.g. -- @calls debitAccount,creditAccount)."
            );
        }

        // Build the call lines — each callee receives the same params as this method
        $callLines = [];
        foreach ($calls as $callee) {
            // Forward matching params if the param name appears in this method's params
            $callLines[] = "            \$this->{$callee}(...func_get_args());";
        }
        $callStr = implode("\n", $callLines);

        // For :transaction methods the params are not auto-forwarded generically —
        // the user declares them explicitly and we call each sub-method with $this->method($arg)
        // For simplicity, emit individual $this->callee() calls without args;
        // the user can use @param to override the call signature.
        $callLinesSimple = [];
        foreach ($calls as $callee) {
            $callLinesSimple[] = "            \$this->{$callee}();";
        }

        // If the query has params, pass them through to all callees
        if (!empty($query->params)) {
            $paramPassStr = implode(', ', array_map(fn($p) => "\${$p->name}", $query->params));
            $callLinesSimple = [];
            foreach ($calls as $callee) {
                $callLinesSimple[] = "            \$this->{$callee}({$paramPassStr});";
            }
        }
        $callStr = implode("\n", $callLinesSimple);

        return <<<PHP
{$docblock}
    public {$signature}
    {
        \$this->pdo->beginTransaction();
        try {
{$callStr}
            \$this->pdo->commit();
        } catch (\Throwable \$e) {
            \$this->pdo->rollBack();
            throw \$e;
        }
    }
PHP;
    }

    /**
     * Normalise SQL into a single-line PHP single-quoted string literal.
     */
    private function renderSqlLiteral(string $sql): string
    {
        $oneLine = preg_replace('/\s+/', ' ', trim($sql)) ?? $sql;
        $escaped = str_replace("'", "\\'", $oneLine);
        return "'{$escaped}'";
    }
}
