<?php

declare(strict_types=1);

namespace SqlcPhp\Generator;

use SqlcPhp\Parser\QueryDefinition;
use SqlcPhp\Resolver\ResolvedColumn;

/**
 * Generates a PHP readonly DTO for the result set of a query
 * that doesn't map 1:1 to a single table model.
 *
 * Naming convention: {QueryName}Row  (e.g. GetUserWithRoleRow)
 */
class ResultDtoGenerator
{
    public function __construct(
        private readonly string $namespace,
    ) {}

    /**
     * Returns the DTO class name for a given query.
     */
    public function dtoClassName(QueryDefinition $query): string
    {
        return ucfirst($query->name) . 'Row';
    }

    /**
     * Generate the PHP code for the result DTO.
     *
     * @return array{className: string, code: string}
     */
    public function generate(QueryDefinition $query): array
    {
        $className = $this->dtoClassName($query);
        $columns   = $query->resultColumns;

        $props    = [];
        $fromArgs = [];

        foreach ($columns as $col) {
            $props[]    = "        public {$col->phpType} \${$col->alias},";
            $fromArgs[] = $this->buildCast($col);
        }

        $propsStr    = implode("\n", $props);
        $fromArgsStr = implode("\n", $fromArgs);

        $sourceDescription = $this->buildSourceDescription($columns);

        $code = <<<PHP
<?php

declare(strict_types=1);

namespace {$this->namespace};

/**
 * Result DTO for the `{$query->name}` query.
 * {$sourceDescription}
 * Generated by sqlc-php — do not edit manually.
 */
readonly class {$className}
{
    public function __construct(
{$propsStr}
    ) {}

    /**
     * Hydrate from a PDO result row (associative array).
     *
     * @param array<string, mixed> \$row
     */
    public static function fromRow(array \$row): self
    {
        return new self(
{$fromArgsStr}
        );
    }
}
PHP;

        return ['className' => $className, 'code' => $code];
    }

    private function buildCast(ResolvedColumn $col): string
    {
        $base     = ltrim($col->phpType, '?');
        $access   = "\$row['{$col->alias}']";
        $nullable = str_starts_with($col->phpType, '?');

        if ($nullable) {
            return match($base) {
                'int'   => "            isset({$access}) ? (int) {$access} : null,",
                'float' => "            isset({$access}) ? (float) {$access} : null,",
                'bool'  => "            isset({$access}) ? (bool) {$access} : null,",
                default => "            {$access} ?? null,",
            };
        }

        return match($base) {
            'int'   => "            (int) {$access},",
            'float' => "            (float) {$access},",
            'bool'  => "            (bool) {$access},",
            'mixed' => "            {$access},",
            default => "            (string) {$access},",
        };
    }

    private function buildSourceDescription(array $columns): string
    {
        $tables = array_unique(
            array_filter(array_map(fn($c) => $c->tableName, $columns))
        );

        if (empty($tables)) return 'Sources: unknown.';

        return 'Sources: ' . implode(', ', $tables) . '.';
    }
}
